"""
AI Yoga Instructor using Computer Vision - Main App Entry Point.
Streamlit application incorporating real-time hierarchical pose tracking, joint angle math,
offline audio coaching, candidate confidence leaderboards, pose hold timers, and wellness recommendations.
"""

import os
import re
import cv2
import time
import numpy as np
import streamlit as st
from PIL import Image
from pathlib import Path
import streamlit.components.v1 as components

# Core imports
from yoga_config import CAMERA_INDEX, POSE_DATABASE
from pose_detector import PoseDetector
from yoga_analyzer import YogaAnalyzer
from voice_coach import VoiceCoach
from recommendation_engine import YogaRecommendationEngine
from session_logger import SessionLogger
from utils.ui_components import apply_premium_styles, render_title_section, draw_card
from utils.image_preprocessor import ImagePreprocessor
from utils.pose_statistics import load_statistics

# Initialize directories
os.makedirs("uploads", exist_ok=True)
os.makedirs("assets", exist_ok=True)
os.makedirs("data", exist_ok=True)

# ---------------------------------------------------------------------------
# Load dataset-derived pose statistics (if available)
# ---------------------------------------------------------------------------
_STATS_PATH = Path(__file__).parent / "data" / "pose_stats.json"


@st.cache_data
def load_pose_stats():
    """Load pose_stats.json generated by build_pose_database.py."""
    stats = load_statistics(_STATS_PATH)
    if stats:
        print(f"[APP] Loaded dataset pose statistics from {_STATS_PATH}")
    return stats


def get_class_angle_distribution(class_name: str) -> dict | None:
    """
    Return per-joint angle statistics for a given class.

    Returns dict like:
        {"left_knee": {"mean": 95.2, "std": 8.1, "min": 72.0, "max": 120.0}, ...}
    or None if stats are not available for that class.
    """
    stats = load_pose_stats()
    if not stats:
        return None
    cls_data = stats.get("classes", {}).get(class_name)
    if not cls_data:
        return None
    return cls_data.get("joints")


def get_dataset_threshold(pose_key: str) -> float | None:
    """
    Return the dataset-derived confidence threshold for a pose, or None
    if no dataset stats are available for this pose.
    """
    stats = load_pose_stats()
    if not stats:
        return None
    cls_data = stats.get("classes", {}).get(pose_key)
    if cls_data:
        return cls_data.get("confidence_threshold")
    return None


def normalize_youtube_url(video_value: str | None) -> str | None:
    """Normalize YouTube URLs so the player works with watch, embed, and youtu.be links."""
    if not video_value:
        return None

    value = str(video_value).strip()
    if not value:
        return None

    if value.startswith(("http://", "https://")):
        if "youtu.be/" in value:
            video_id = value.split("youtu.be/")[-1].split("?", 1)[0].split("&", 1)[0]
            return f"https://www.youtube.com/watch?v={video_id}"
        if "youtube.com/embed/" in value:
            video_id = value.split("youtube.com/embed/")[-1].split("?", 1)[0].split("&", 1)[0]
            return f"https://www.youtube.com/watch?v={video_id}"
        if "youtube.com/watch?v=" in value:
            return value
        if "youtube.com/shorts/" in value:
            video_id = value.split("youtube.com/shorts/")[-1].split("?", 1)[0].split("&", 1)[0]
            return f"https://www.youtube.com/watch?v={video_id}"
        return value

    if re.fullmatch(r"[A-Za-z0-9_-]{11}", value):
        return f"https://www.youtube.com/watch?v={value}"

    return None


def render_pose_card(pose: dict) -> None:
    """Render a clean, modern pose recommendation card with lazy tutorial playback."""
    video_url = normalize_youtube_url(pose.get("youtube_id"))

    with st.expander(f"🧘 {pose['name']}  •  {pose['difficulty']}", expanded=False):
        st.markdown("<div class='glass-card recommendation-card'>", unsafe_allow_html=True)

        left, right = st.columns([1.05, 0.95], gap="large")
        with left:
            image_path = pose.get("image_path") or "assets/recommendation/mountain.svg"
            st.image(image_path, use_column_width=True, caption=pose.get("category", "Wellness"))
            st.write(pose.get("description", "A supportive yoga posture for your wellness goal."))
            st.markdown("<div class='mini-section'>", unsafe_allow_html=True)
            st.markdown("<h5 class='mini-title'>Why it helps</h5>", unsafe_allow_html=True)
            for benefit in pose.get("benefits", []):
                st.markdown(f"- ✨ {benefit}", unsafe_allow_html=True)
            st.markdown("</div>", unsafe_allow_html=True)

        with right:
            st.markdown("<div class='mini-section'>", unsafe_allow_html=True)
            st.markdown("<h5 class='mini-title'>Step-by-step guidance</h5>", unsafe_allow_html=True)
            for step in pose.get("steps", []):
                st.markdown(f"1. {step}", unsafe_allow_html=True)
            st.markdown("</div>", unsafe_allow_html=True)

            st.markdown("<div class='mini-section'>", unsafe_allow_html=True)
            st.markdown("<h5 class='mini-title'>Video Tutorial</h5>", unsafe_allow_html=True)
            with st.expander("▶ Open Video Player", expanded=False):
                if video_url:
                    st.markdown(f"**[🔗 Click here to watch on YouTube]({video_url})**")
                    st.video(video_url)
                else:
                    st.error("Tutorial video link is unavailable.")
            st.markdown("</div>", unsafe_allow_html=True)

        st.markdown("</div>", unsafe_allow_html=True)

# Page Configuration
st.set_page_config(
    page_title="AI Yoga Instructor",
    page_icon="🧘",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Apply custom CSS stylesheet
apply_premium_styles()

# Global module initializations (Cached to avoid re-instantiation on rerun)
@st.cache_resource
def get_pose_detector():
    return PoseDetector()

@st.cache_resource
def get_upload_pose_detector():
    # Instantiates a highly tolerant detector specifically optimized for sketches, drawings, cartoons, and illustrations
    return PoseDetector(min_detection_confidence=0.15, min_tracking_confidence=0.15)

@st.cache_resource
def get_yoga_analyzer():
    return YogaAnalyzer()

@st.cache_resource
def get_voice_coach():
    return VoiceCoach()

detector = get_pose_detector()
upload_detector = get_upload_pose_detector()
analyzer = get_yoga_analyzer()
voice_coach = get_voice_coach()

# --- Sidebar Navigation ---
st.sidebar.markdown(
    """
    <div style="text-align: center; margin-bottom: 2rem;">
        <h2 style="color: #c084fc; font-weight: 800; margin-bottom:0;">YOGA AI</h2>
        <span style="color: #9ca3af; font-size: 0.85rem;">Computer Vision Coaching</span>
    </div>
    """,
    unsafe_allow_html=True
)

page = st.sidebar.radio(
    "NAVIGATION",
    ["Home", "Live Yoga Mode", "Upload Image Mode", "Yoga Recommendation Mode", "About Project"]
)



# Active Session state initializations
if "session_active" not in st.session_state:
    st.session_state.session_active = False
if "pose_hold_start" not in st.session_state:
    st.session_state.pose_hold_start = None
if "pose_hold_time" not in st.session_state:
    st.session_state.pose_hold_time = 0.0
if "last_milestone_voiced" not in st.session_state:
    st.session_state.last_milestone_voiced = 0

# =========================================================================
# PAGE: HOME
# =========================================================================
if page == "Home":
    render_title_section("AI YOGA INSTRUCTOR", "Hierarchical Computer Vision Yoga Coaching Companion")
    
    # Showcase banner card
    st.markdown(
        """
        <div class="glass-card" style="border-left: 5px solid #8b5cf6;">
            <h2 style="color: #c084fc; margin-top: 0;">Step Onto the Mat & Let AI Guide You</h2>
            <p style="font-size: 1.1rem; line-height: 1.6; color: #d1d5db; margin-bottom: 0;">
                This system utilizes advanced computer vision via MediaPipe and joint-angle biomechanical calculations 
                to analyze your yoga postures. Our new **Hierarchical Pose Classifier** categorizes your body posture first 
                (Standing, Sitting, Backbend, Folded, Balancing) and then scores candidate poses using temporal smoothing, 
                generating live voice corrections, a stability score, and an interactive hold timer.
            </p>
        </div>
        """,
        unsafe_allow_html=True
    )
    
    st.markdown("### Supported Yoga Postures (9 Poses Database)")
    
    # Grid of Poses
    col1, col2 = st.columns(2)
    
    poses_info = list(POSE_DATABASE.items())
    
    for idx, (pose_key, data) in enumerate(poses_info):
        target_col = col1 if idx % 2 == 0 else col2
        with target_col:
            pose_name = data["display_name"]
            desc = data["entry_guidance"]
            category = data["category"]
            
            body_html = f"""
            <span style="background: rgba(139, 92, 246, 0.25); color: #c084fc; padding: 0.15rem 0.5rem; border-radius: 4px; font-size: 0.75rem; font-weight: 600;">{category}</span>
            <p style="color: #9ca3af; font-size: 0.95rem; line-height: 1.5; margin-top: 0.5rem; margin-bottom: 0;">{desc}</p>
            """
            draw_card(pose_name, body_html)

# =========================================================================
# PAGE: LIVE YOGA MODE  (Camera Capture — works on ALL networks)
# =========================================================================
elif page == "Live Yoga Mode":
    render_title_section("LIVE YOGA COACH", "Camera-Based Pose Tracker with AI Corrections")

    # Instructions Card
    st.markdown(
        """
        <div class="glass-card" style="margin-bottom: 2.0rem;">
            <h4 style="margin-top: 0; color: #818cf8; margin-bottom: 0.5rem;">How It Works</h4>
            <ul style="color: #9ca3af; margin-bottom: 0; padding-left: 1.2rem; line-height: 1.7;">
                <li><b>Step 1:</b> Allow camera access when your browser asks.</li>
                <li><b>Step 2:</b> Get into your yoga pose in front of the camera.</li>
                <li><b>Step 3:</b> Click <b>"📸 Take Photo"</b> to capture and analyze your pose.</li>
                <li><b>Step 4:</b> Review AI feedback, corrections, and scores.</li>
                <li><b>Step 5:</b> Click <b>"Clear photo"</b> and retake to track improvement!</li>
            </ul>
        </div>
        """,
        unsafe_allow_html=True
    )

    # --- Settings Panel ---
    col_settings = st.columns(3)
    with col_settings[0]:
        selected_pose = st.selectbox(
            "Select Target Posture",
            ["Auto-Detect"] + [data["display_name"] for data in POSE_DATABASE.values()]
        )
    with col_settings[1]:
        show_debug = st.checkbox("Show AI Diagnostics", value=True)
    with col_settings[2]:
        st.markdown(f"**Poses Database:** {len(POSE_DATABASE)} poses")

    st.markdown("---")

    # --- Camera Capture ---
    camera_image = st.camera_input("📸 Capture your yoga pose")

    if camera_image is not None:
        # Decode the captured image
        img_bytes = camera_image.getvalue()
        img_array = np.frombuffer(img_bytes, dtype=np.uint8)
        img_cv = cv2.imdecode(img_array, cv2.IMREAD_COLOR)

        if img_cv is not None:
            # Mirror for intuitive feedback
            img_cv = cv2.flip(img_cv, 1)

            # Process with MediaPipe
            rgb = cv2.cvtColor(img_cv, cv2.COLOR_BGR2RGB)
            results = detector.process(rgb)

            col_img, col_analysis = st.columns([1.2, 1])

            with col_img:
                if results.pose_landmarks:
                    annotated = img_cv.copy()
                    detector.draw_landmarks(annotated, results.pose_landmarks[0])

                    # Draw metrics on image
                    lm_list = results.pose_landmarks[0]
                    analysis = analyzer.analyze(detector, lm_list, selected_pose, is_static=True)

                    h, w = annotated.shape[:2]
                    pose_key = analysis["detected_pose"]
                    accuracy = analysis["accuracy"]
                    stability = analysis["stability"]
                    pose_display = POSE_DATABASE[pose_key]["display_name"] if pose_key != "unknown" else "Analyzing..."

                    # Top bar
                    cv2.rectangle(annotated, (0, 0), (w, 45), (17, 24, 39), -1)
                    cv2.putText(annotated, f"Pose: {pose_display}", (10, 32), cv2.FONT_HERSHEY_SIMPLEX, 0.8, (252, 132, 192), 2)

                    # Bottom bar
                    cv2.rectangle(annotated, (0, h - 50), (w, h), (17, 24, 39), -1)
                    cv2.putText(annotated, f"Confidence: {int(accuracy)}%", (15, h - 18), cv2.FONT_HERSHEY_SIMPLEX, 0.7, (182, 114, 244), 2)
                    cv2.putText(annotated, f"Stability: {int(stability)}%", (w // 2 + 10, h - 18), cv2.FONT_HERSHEY_SIMPLEX, 0.7, (248, 140, 129), 2)

                    st.image(cv2.cvtColor(annotated, cv2.COLOR_BGR2RGB), use_container_width=True)
                    st.caption("✅ Pose detected and analyzed successfully")
                else:
                    st.image(cv2.cvtColor(img_cv, cv2.COLOR_BGR2RGB), use_container_width=True)
                    st.warning("⚠ No pose detected. Make sure your full body is visible in the frame.")
                    analysis = None

            with col_analysis:
                st.markdown("### 📊 AI Analysis")

                if results.pose_landmarks and analysis:
                    pose_key = analysis["detected_pose"]
                    accuracy = analysis["accuracy"]
                    stability = analysis["stability"]
                    category = analysis["category"]

                    # Pose Name
                    if pose_key != "unknown":
                        pose_display = POSE_DATABASE[pose_key]["display_name"]
                        st.success(f"**Detected:** {pose_display}")
                    else:
                        st.info("**Detected:** Pose Uncertain")

                    # Metrics Grid
                    m1, m2 = st.columns(2)
                    with m1:
                        confidence_color = "#10b981" if accuracy >= 70 else "#f59e0b" if accuracy >= 40 else "#ef4444"
                        st.markdown(f"""
                        <div class="metric-tile" style="border-color: {confidence_color};">
                            <div class="metric-val" style="color: {confidence_color}; font-size: 2.2rem;">{accuracy:.0f}%</div>
                            <div class="metric-label">Confidence</div>
                        </div>
                        """, unsafe_allow_html=True)
                    with m2:
                        stability_color = "#818cf8"
                        st.markdown(f"""
                        <div class="metric-tile" style="border-color: {stability_color};">
                            <div class="metric-val" style="color: {stability_color}; font-size: 2.2rem;">{stability:.0f}%</div>
                            <div class="metric-label">Stability</div>
                        </div>
                        """, unsafe_allow_html=True)

                    st.markdown(f"**Category:** {category}")

                    # Corrections
                    if analysis.get("corrections"):
                        st.markdown("#### 🧘 AI Coaching Feedback")
                        for i, correction in enumerate(analysis["corrections"][:3]):
                            icon = "🔴" if i == 0 else "🟡" if i == 1 else "🟢"
                            st.markdown(f"{icon} {correction['message']}")
                    else:
                        st.markdown("""
                        <div class="glass-card" style="border-color: rgba(16, 185, 129, 0.4); text-align: center; padding: 1rem;">
                            <div style="font-size: 1.5rem;">✨</div>
                            <div style="color: #10b981; font-weight: 700; font-size: 1.1rem;">Perfect Alignment!</div>
                            <div style="color: #9ca3af; font-size: 0.9rem;">Great form — maintain this posture.</div>
                        </div>
                        """, unsafe_allow_html=True)

                    # Debug Panel
                    if show_debug:
                        # Candidate Scores
                        candidate_scores = analysis.get("candidate_scores", {})
                        if candidate_scores:
                            with st.expander("📊 Candidate Pose Scores", expanded=True):
                                sorted_candidates = sorted(candidate_scores.items(), key=lambda x: x[1], reverse=True)
                                for pname, score in sorted_candidates[:5]:
                                    bar_color = "#10b981" if score >= 70 else "#f59e0b" if score >= 40 else "#ef4444"
                                    st.markdown(f"""
                                    <div style="margin-bottom: 0.4rem;">
                                        <div style="display:flex;justify-content:space-between;margin-bottom:0.15rem;">
                                            <span style="color:#e5e7eb;font-size:0.85rem;">{pname}</span>
                                            <b style="color:#e5e7eb;font-size:0.85rem;">{score:.0f}%</b>
                                        </div>
                                        <div style="background:rgba(255,255,255,0.05);height:6px;border-radius:3px;">
                                            <div style="background:{bar_color};width:{min(score, 100)}%;height:6px;border-radius:3px;"></div>
                                        </div>
                                    </div>
                                    """, unsafe_allow_html=True)

                        # Joint Angles
                        if analysis.get("angles"):
                            with st.expander("🦴 Joint Angles"):
                                st.json(analysis["angles"])

                        # Rejected Poses
                        rejected = analysis.get("rejected_poses", {})
                        if rejected:
                            with st.expander("🚫 Rejected Poses"):
                                for pname, reasons in rejected.items():
                                    st.write(f"**{pname}:** {', '.join(reasons)}")

                        # Body Orientation
                        orientation = analysis.get("orientation", {})
                        if orientation:
                            with st.expander("📐 Body Orientation"):
                                st.json(orientation)
                else:
                    st.markdown("""
                    <div class="glass-card" style="text-align: center; padding: 2rem;">
                        <div style="font-size: 2rem; margin-bottom: 0.5rem;">📷</div>
                        <div style="color: #9ca3af; font-size: 1rem;">No pose detected in this frame.</div>
                        <div style="color: #6b7280; font-size: 0.85rem; margin-top: 0.5rem;">
                            Tips: Stand back so your full body is visible. Ensure good lighting.
                        </div>
                    </div>
                    """, unsafe_allow_html=True)
    else:
        # Empty state — waiting for camera capture
        st.markdown("""
        <div class="glass-card" style="text-align: center; padding: 3rem; border-color: rgba(139, 92, 246, 0.3);">
            <div style="font-size: 3rem; margin-bottom: 1rem;">🎥</div>
            <div style="color: #c084fc; font-size: 1.4rem; font-weight: 700; margin-bottom: 0.5rem;">Camera Ready</div>
            <div style="color: #9ca3af; font-size: 1rem; line-height: 1.6;">
                Your browser will ask for camera permission.<br>
                Get into your yoga pose, then click <b>"📸 Take Photo"</b> above to begin AI analysis.
            </div>
        </div>
        """, unsafe_allow_html=True)

# =========================================================================
# PAGE: UPLOAD IMAGE MODE
# =========================================================================
elif page == "Upload Image Mode":
    render_title_section("IMAGE ANALYZER", "Enhanced AI Diagnostics for Static Posture Analysis")
    
    st.markdown(
        """
        <div class="glass-card" style="margin-bottom: 2.0rem;">
            <h4 style="margin-top: 0; color: #818cf8; margin-bottom: 0.5rem;">Upload Guidelines</h4>
            <ul style="color: #9ca3af; margin-bottom: 0; padding-left: 1.2rem; line-height: 1.5;">
                <li>Supported formats: JPG, JPEG, PNG</li>
                <li>Ensure the full body is visible in the frame</li>
                <li>Good lighting helps with pose detection accuracy</li>
                <li>The system uses multi-stage preprocessing to enhance low-quality images</li>
            </ul>
        </div>
        """,
        unsafe_allow_html=True
    )
    
    uploaded_file = st.file_uploader("Choose an image...", type=["jpg", "jpeg", "png"])

    if uploaded_file:
        try:
            # Process uploaded image
            img_cv = ImagePreprocessor.process_to_cv2(uploaded_file)
            if img_cv is not None:
                col1, col2 = st.columns([1, 1])
                with col1:
                    st.markdown("### Source Image & Detection")
                    
                    # Use enhanced preprocessing pipeline for uploaded images
                    try:
                        # Run enhanced preprocessing pipeline directly from memory
                        success, processed_img, stage_name, results, original_resized = ImagePreprocessor.run_detection_pipeline(img_cv, upload_detector)
                        
                        if success and results and results.pose_landmarks:
                            annotated = processed_img.copy()
                            upload_detector.draw_landmarks(annotated, results.pose_landmarks[0])
                            st.image(cv2.cvtColor(annotated, cv2.COLOR_BGR2RGB), use_container_width=True)
                            st.caption(f"✓ Pose detected on {stage_name}")
                        else:
                            # Show original image if detection failed
                            st.image(cv2.cvtColor(img_cv, cv2.COLOR_BGR2RGB), use_container_width=True)
                            st.warning("⚠ No pose skeleton detected in any preprocessing stage.")
                    except Exception as e:
                        st.error(f"Preprocessing error: {str(e)}")
                        st.image(cv2.cvtColor(img_cv, cv2.COLOR_BGR2RGB), use_container_width=True)
                
                with col2:
                    st.markdown("### Diagnostic Metrics")
                    
                    # Use robust results if successful, else fallback to basic
                    target_results = results if (success and results and hasattr(results, 'pose_landmarks') and results.pose_landmarks) else None
                    if not target_results:
                        target_results = upload_detector.process(cv2.cvtColor(img_cv, cv2.COLOR_BGR2RGB))
                    
                    if target_results and target_results.pose_landmarks:
                        try:
                            analysis = analyzer.analyze(upload_detector, target_results.pose_landmarks[0], None, is_static=True)
                            
                            # Display metrics
                            col_m1, col_m2 = st.columns(2)
                            with col_m1:
                                st.metric("Confidence", f"{analysis['confidence']:.1f}%")
                            with col_m2:
                                st.metric("Stability", f"{analysis['stability']:.1f}%")
                            
                            if analysis.get("is_low_confidence", False):
                                st.warning("⚠ Pose Uncertain — confidence below threshold")
                            
                            detected = analysis['detected_pose']
                            if detected != 'unknown':
                                display = POSE_DATABASE.get(detected, {}).get('display_name', detected)
                                st.success(f"**Detected Pose:** {display}")
                            else:
                                st.info("**Detected Pose:** Pose Uncertain")
                            
                            st.write(f"**Category:** {analysis['category']}")
                            if analysis.get('category_reason'):
                                st.caption(f"Reason: {analysis['category_reason']}")
                            
                            # Debug Panel: Top Candidate Poses
                            candidate_scores = analysis.get("candidate_scores", {})
                            if candidate_scores:
                                st.markdown("**✅ Accepted Candidate Poses:**")
                                sorted_candidates = sorted(candidate_scores.items(), key=lambda x: x[1], reverse=True)
                                for pose_name, score in sorted_candidates[:5]:
                                    st.write(f"- {pose_name} → {score:.1f}%")
                            
                            # Debug Panel: Rejected Poses
                            rejected = analysis.get("rejected_poses", {})
                            if rejected:
                                with st.expander("🚫 Rejected Poses (Hard Filter)"):
                                    for pose_name, reasons in rejected.items():
                                        st.write(f"**{pose_name}:**")
                                        for r in reasons:
                                            st.write(f"  • {r}")
                            
                            # Body Orientation Metrics
                            orientation = analysis.get("orientation", {})
                            if orientation:
                                with st.expander("📐 Body Orientation Metrics"):
                                    st.json(orientation)
                            
                            if analysis.get("angles"):
                                with st.expander("🦴 Joint Angles"):
                                    st.json(analysis["angles"])
                            
                            if analysis.get("corrections"):
                                st.write("**Corrections:**")
                                for correction in analysis["corrections"][:3]:
                                    st.write(f"• {correction['message']}")
                        except Exception as e:
                            st.warning(f"Analysis error: {str(e)}")
                    else:
                        st.info("No pose skeleton detected. Try:\n- Better lighting\n- Full body in frame\n- Higher quality image")
            else:
                st.error("Failed to decode image. Try:\n- Different format (JPG/PNG)\n- Smaller file size\n- Standard resolution")
        except Exception as e:
            st.error(f"Error processing upload: {str(e)}")
            st.info("Please try uploading a different image or check the file format.")
    else:
        st.info("Upload a clear image to begin hierarchical posture classification.")

# =========================================================================
# PAGE: YOGA RECOMMENDATION MODE
# =========================================================================
elif page == "Yoga Recommendation Mode":
    # Netflix-style card CSS for recommendation page
    st.markdown(
        """
        <style>
        .rec-title {
            font-size: 2.8rem;
            font-weight: 800;
            background: linear-gradient(90deg, #38bdf8 0%, #a78bfa 50%, #f472b6 100%);
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
            text-align: center;
            margin-bottom: 0.15rem;
        }
        .rec-subtitle {
            text-align: center;
            color: #9ca3af;
            font-size: 1.1rem;
            margin-bottom: 1.5rem;
        }
        .video-card {
            background: rgba(15, 23, 42, 0.75);
            border: 1px solid rgba(56, 189, 248, 0.18);
            border-radius: 16px;
            overflow: hidden;
            margin-bottom: 1.5rem;
            transition: border-color 0.3s ease, box-shadow 0.3s ease;
        }
        .video-card:hover {
            border-color: rgba(56, 189, 248, 0.45);
            box-shadow: 0 0 24px rgba(56, 189, 248, 0.12);
        }
        .video-card-body {
            padding: 1rem 1.1rem 1.1rem 1.1rem;
        }
        .video-card-title-row {
            display: flex;
            justify-content: space-between;
            align-items: flex-start;
            margin-bottom: 0.45rem;
            gap: 0.5rem;
        }
        .video-card-title {
            font-size: 1rem;
            font-weight: 700;
            color: #e2e8f0;
            line-height: 1.35;
        }
        .badge {
            display: inline-block;
            padding: 0.15rem 0.55rem;
            border-radius: 6px;
            font-size: 0.7rem;
            font-weight: 700;
            white-space: nowrap;
            flex-shrink: 0;
        }
        .badge-beginner { background: rgba(16, 185, 129, 0.18); color: #34d399; border: 1px solid rgba(16, 185, 129, 0.35); }
        .badge-intermediate { background: rgba(245, 158, 11, 0.18); color: #fbbf24; border: 1px solid rgba(245, 158, 11, 0.35); }
        .badge-advanced { background: rgba(239, 68, 68, 0.18); color: #f87171; border: 1px solid rgba(239, 68, 68, 0.35); }
        .video-card-desc {
            font-size: 0.85rem;
            color: #94a3b8;
            line-height: 1.45;
            margin-bottom: 0.6rem;
        }
        .video-card-benefits {
            font-size: 0.78rem;
            color: #38bdf8;
            font-weight: 600;
            margin-bottom: 0.75rem;
        }
        .video-card-tags {
            display: flex;
            flex-wrap: wrap;
            gap: 0.4rem;
            align-items: center;
        }
        .tag-pill {
            display: inline-block;
            padding: 0.18rem 0.55rem;
            border-radius: 999px;
            font-size: 0.68rem;
            font-weight: 600;
            background: rgba(255, 255, 255, 0.06);
            color: #9ca3af;
            border: 1px solid rgba(255, 255, 255, 0.08);
        }
        .watch-btn {
            display: inline-flex;
            align-items: center;
            gap: 0.3rem;
            padding: 0.2rem 0.6rem;
            border-radius: 999px;
            font-size: 0.7rem;
            font-weight: 700;
            background: rgba(56, 189, 248, 0.15);
            color: #38bdf8;
            border: 1px solid rgba(56, 189, 248, 0.3);
            text-decoration: none;
            cursor: pointer;
        }
        </style>
        """,
        unsafe_allow_html=True
    )

    # --- Page Header ---
    st.markdown('<div class="rec-title">Yoga Search & Discovery</div>', unsafe_allow_html=True)
    st.markdown('<div class="rec-subtitle">Find yoga tutorials for wellness and fitness goals</div>', unsafe_allow_html=True)

    # --- Search Bar ---
    if "rec_search_input" not in st.session_state:
        st.session_state.rec_search_input = ""

    col_input, col_btn = st.columns([4, 1])
    with col_input:
        search_query = st.text_input(
            "Search your wellness goal",
            placeholder="e.g. stress relief, back pain, weight loss, flexibility...",
            label_visibility="collapsed",
            key="rec_search_input"
        )
    with col_btn:
        st.button("🔍 Search", use_container_width=True)

    # --- Quick Suggestion Chips ---
    st.markdown("**💡 Quick Suggestions:**")
    suggestions = [
        ("Back Pain", "back pain"),
        ("Stress Relief", "stress relief"),
        ("Flexibility", "flexibility"),
        ("Weight Loss", "weight loss"),
        ("Neck Pain", "neck pain"),
        ("Beginner", "beginner yoga"),
    ]
    
    def set_search_query(val):
        st.session_state.rec_search_input = val

    chip_cols = st.columns(len(suggestions))
    for idx, (label, search_val) in enumerate(suggestions):
        with chip_cols[idx]:
            st.button(label, key=f"suggest_{idx}", on_click=set_search_query, args=(search_val,), use_container_width=True)

    st.divider()

    # --- Results Section ---
    query_text = search_query.strip()

    if query_text:
        st.markdown(f"Results for '*{query_text}*'  &nbsp; **+ AI**", unsafe_allow_html=True)
        st.markdown("")

        videos = YogaRecommendationEngine.get_videos_for_query(query_text)

        if videos:
            # Render in rows of 3 — Netflix-style cards with embedded YouTube
            for i in range(0, len(videos), 3):
                cols = st.columns(3, gap="medium")
                for j in range(3):
                    if i + j < len(videos):
                        video = videos[i + j]
                        video_url = video["url"]
                        parsed_id = YogaRecommendationEngine.extract_youtube_id(video_url)

                        # Difficulty badge class
                        diff = video.get("difficulty", "Beginner")
                        if diff == "Beginner":
                            badge_class = "badge-beginner"
                        elif diff == "Intermediate":
                            badge_class = "badge-intermediate"
                        else:
                            badge_class = "badge-advanced"

                        # Build tag pills HTML
                        tags = video.get("tags", [])
                        duration = video.get("duration", "")
                        tag_pills = ""
                        if tags:
                            for t in tags:
                                tag_pills += f'<span class="tag-pill">{t}</span>'
                        if duration:
                            tag_pills += f'<span class="tag-pill">{duration}</span>'

                        # Benefits text
                        benefits = video.get("benefits", [])
                        benefits_text = " · ".join(benefits) if benefits else ""

                        with cols[j]:
                            # Embedded YouTube player via components.html (bypasses Streamlit's iframe sanitizer)
                            yt_embed_html = f'''
                            <div style="position:relative;padding-bottom:56.25%;height:0;overflow:hidden;border-radius:8px 8px 0 0;">
                                <iframe src="https://www.youtube.com/embed/{parsed_id}"
                                    style="position:absolute;top:0;left:0;width:100%;height:100%;border:none;"
                                    allow="accelerometer;autoplay;clipboard-write;encrypted-media;gyroscope;picture-in-picture"
                                    allowfullscreen></iframe>
                            </div>
                            '''
                            components.html(yt_embed_html, height=200)

                            # Card body with title, badge, description, benefits, tags
                            card_html = f"""
                            <div class="video-card-body">
                                <div class="video-card-title-row">
                                    <span class="video-card-title">{video['title']}</span>
                                    <span class="badge {badge_class}">{diff}</span>
                                </div>
                                <div class="video-card-desc">{video['description']}</div>
                                <div class="video-card-benefits">{benefits_text}</div>
                                <div class="video-card-tags">
                                    {tag_pills}
                                    <a href="{video_url}" target="_blank" class="watch-btn">▶ Watch</a>
                                </div>
                            </div>
                            """
                            st.markdown(card_html, unsafe_allow_html=True)
        else:
            st.warning(f'No tutorials found for "{query_text}". Try one of the quick suggestions above!')
    else:
        # Empty state
        st.markdown("---")
        st.markdown(
            """
            ### 🧘 Discovery Hub Active

            Type any wellness goal in the search bar above to find targeted yoga tutorials.

            **Try searching for:**
            - *"back pain"* — stretches for spinal relief
            - *"stress relief"* — calming breathing flows
            - *"weight loss"* — power vinyasa flows
            - *"flexibility"* — deep hip and hamstring stretches
            - *"beginner yoga"* — gentle starter routines
            """
        )


# =========================================================================
# PAGE: ABOUT PROJECT
# =========================================================================
elif page == "About Project":
    render_title_section("PROJECT METRICS", "Architecture & Technical Specifications")

    col_stack, col_arch = st.columns([1, 1])

    with col_stack:
        st.markdown("### System Architecture")
        
        arch_details = """
        <p style="color:#d1d5db; line-height:1.6; font-size:0.95rem;">
            This system runs entirely locally on Windows to offer real-time computer vision training without sending your camera feed to external cloud servers.
        </p>
        <ul style="color:#9ca3af; font-size:0.95rem; line-height:1.6; padding-left: 1.2rem;">
            <li><b>Hierarchical Category Classifier:</b> Groups body layouts into high-level Categories first before analyzing candidate poses, solving splay conflicts.</li>
            <li><b>Computer Vision Model:</b> MediaPipe Pose Landmarker utilizing full-body landmarks (33 keypoints in 3D).</li>
            <li><b>Biomechanical Features:</b> Angle calculators utilizing vector geometry, slopes, splay lines (NumPy).</li>
            <li><b>Pose locking & Temporal Smoothing:</b> Lock mechanism retaining stable pose classification and majority vote rolling frame buffers preventing pose flickering.</li>
            <li><b>Visibility Warnings:</b> Pauses estimation if crucial joints exit the camera frame boundary.</li>
            <li><b>Vocal Guide:</b> Thread-safe offline pyttsx3, prioritizing single high-priority corrections.</li>
        </ul>
        """
        draw_card("Local Computations", arch_details)

    with col_arch:
        st.markdown("### Tech Stack Used")
        
        stack_html = """
        <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 1rem; font-size: 0.95rem;">
            <div style="background: rgba(255, 255, 255, 0.03); border: 1px solid rgba(255, 255, 255, 0.05); padding: 0.75rem; border-radius: 8px;">
                <b style="color: #c084fc;">Streamlit</b><br>
                <span style="color: #9ca3af;">Frontend Dashboard</span>
            </div>
            <div style="background: rgba(255, 255, 255, 0.03); border: 1px solid rgba(255, 255, 255, 0.05); padding: 0.75rem; border-radius: 8px;">
                <b style="color: #c084fc;">MediaPipe</b><br>
                <span style="color: #9ca3af;">Full Skeleton Extraction</span>
            </div>
            <div style="background: rgba(255, 255, 255, 0.03); border: 1px solid rgba(255, 255, 255, 0.05); padding: 0.75rem; border-radius: 8px;">
                <b style="color: #c084fc;">OpenCV</b><br>
                <span style="color: #9ca3af;">Webcam Capture & Drawing</span>
            </div>
            <div style="background: rgba(255, 255, 255, 0.03); border: 1px solid rgba(255, 255, 255, 0.05); padding: 0.75rem; border-radius: 8px;">
                <b style="color: #c084fc;">pyttsx3</b><br>
                <span style="color: #9ca3af;">Offline Threaded TTS</span>
            </div>
            <div style="background: rgba(255, 255, 255, 0.03); border: 1px solid rgba(255, 255, 255, 0.05); padding: 0.75rem; border-radius: 8px;">
                <b style="color: #c084fc;">NumPy</b><br>
                <span style="color: #9ca3af;">Vector Geometry Calculations</span>
            </div>
            <div style="background: rgba(255, 255, 255, 0.03); border: 1px solid rgba(255, 255, 255, 0.05); padding: 0.75rem; border-radius: 8px;">
                <b style="color: #c084fc;">JSON Logs</b><br>
                <span style="color: #9ca3af;">Session Tracker Data</span>
            </div>
        </div>
        """
        draw_card("Developer Specifications", stack_html)

# Add dynamic project footer
st.sidebar.markdown(
    """
    <div style="position: fixed; bottom: 1rem; width: 14%; text-align: center; border-top: 1px solid rgba(255,255,255,0.05); padding-top:0.5rem;">
        <span style="color:#4b5563; font-size:0.75rem;">AI Yoga Coach v2.0.0</span>
    </div>
    """,
    unsafe_allow_html=True
)
