"""
AI Yoga Instructor using Computer Vision - Main App Entry Point.
Streamlit application incorporating real-time hierarchical pose tracking, joint angle math,
offline audio coaching, candidate confidence leaderboards, pose hold timers, and wellness recommendations.
"""

import os
import re
import cv2
import time
import numpy as np
import streamlit as st
from PIL import Image
from pathlib import Path
import streamlit.components.v1 as components
# No more WebRTC or AV imports

# Core imports
from yoga_config import CAMERA_INDEX, POSE_DATABASE
from pose_detector import PoseDetector
from yoga_analyzer import YogaAnalyzer
from voice_coach import VoiceCoach
from recommendation_engine import YogaRecommendationEngine
from session_logger import SessionLogger
from utils.ui_components import apply_premium_styles, render_title_section, draw_card
from utils.image_preprocessor import ImagePreprocessor
from utils.pose_statistics import load_statistics
from yoga_similarity_engine import PoseSimilarityEngine

# Initialize directories
os.makedirs("uploads", exist_ok=True)
os.makedirs("assets", exist_ok=True)
os.makedirs("data", exist_ok=True)

# ---------------------------------------------------------------------------
# Load dataset-derived pose statistics (if available)
# ---------------------------------------------------------------------------
_STATS_PATH = Path(__file__).parent / "data" / "pose_stats.json"


@st.cache_data
def load_pose_stats():
    """Load pose_stats.json generated by build_pose_database.py."""
    stats = load_statistics(_STATS_PATH)
    if stats:
        print(f"[APP] Loaded dataset pose statistics from {_STATS_PATH}")
    return stats


def get_class_angle_distribution(class_name: str) -> dict | None:
    """
    Return per-joint angle statistics for a given class.

    Returns dict like:
        {"left_knee": {"mean": 95.2, "std": 8.1, "min": 72.0, "max": 120.0}, ...}
    or None if stats are not available for that class.
    """
    stats = load_pose_stats()
    if not stats:
        return None
    cls_data = stats.get("classes", {}).get(class_name)
    if not cls_data:
        return None
    return cls_data.get("joints")


def get_dataset_threshold(pose_key: str) -> float | None:
    """
    Return the dataset-derived confidence threshold for a pose, or None
    if no dataset stats are available for this pose.
    """
    stats = load_pose_stats()
    if not stats:
        return None
    cls_data = stats.get("classes", {}).get(pose_key)
    if cls_data:
        return cls_data.get("confidence_threshold")
    return None


def normalize_youtube_url(video_value: str | None) -> str | None:
    """Normalize YouTube URLs so the player works with watch, embed, and youtu.be links."""
    if not video_value:
        return None

    value = str(video_value).strip()
    if not value:
        return None

    if value.startswith(("http://", "https://")):
        if "youtu.be/" in value:
            video_id = value.split("youtu.be/")[-1].split("?", 1)[0].split("&", 1)[0]
            return f"https://www.youtube.com/watch?v={video_id}"
        if "youtube.com/embed/" in value:
            video_id = value.split("youtube.com/embed/")[-1].split("?", 1)[0].split("&", 1)[0]
            return f"https://www.youtube.com/watch?v={video_id}"
        if "youtube.com/watch?v=" in value:
            return value
        if "youtube.com/shorts/" in value:
            video_id = value.split("youtube.com/shorts/")[-1].split("?", 1)[0].split("&", 1)[0]
            return f"https://www.youtube.com/watch?v={video_id}"
        return value

    if re.fullmatch(r"[A-Za-z0-9_-]{11}", value):
        return f"https://www.youtube.com/watch?v={value}"

    return None


def render_pose_card(pose: dict) -> None:
    """Render a clean, modern pose recommendation card with lazy tutorial playback."""
    video_url = normalize_youtube_url(pose.get("youtube_id"))

    with st.expander(f"🧘 {pose['name']}  •  {pose['difficulty']}", expanded=False):
        st.markdown("<div class='glass-card recommendation-card'>", unsafe_allow_html=True)

        left, right = st.columns([1.05, 0.95], gap="large")
        with left:
            image_path = pose.get("image_path") or "assets/recommendation/mountain.svg"
            st.image(image_path, use_column_width=True, caption=pose.get("category", "Wellness"))
            st.write(pose.get("description", "A supportive yoga posture for your wellness goal."))
            st.markdown("<div class='mini-section'>", unsafe_allow_html=True)
            st.markdown("<h5 class='mini-title'>Why it helps</h5>", unsafe_allow_html=True)
            for benefit in pose.get("benefits", []):
                st.markdown(f"- ✨ {benefit}", unsafe_allow_html=True)
            st.markdown("</div>", unsafe_allow_html=True)

        with right:
            st.markdown("<div class='mini-section'>", unsafe_allow_html=True)
            st.markdown("<h5 class='mini-title'>Step-by-step guidance</h5>", unsafe_allow_html=True)
            for step in pose.get("steps", []):
                st.markdown(f"1. {step}", unsafe_allow_html=True)
            st.markdown("</div>", unsafe_allow_html=True)

            st.markdown("<div class='mini-section'>", unsafe_allow_html=True)
            st.markdown("<h5 class='mini-title'>Video Tutorial</h5>", unsafe_allow_html=True)
            with st.expander("▶ Open Video Player", expanded=False):
                if video_url:
                    st.markdown(f"**[🔗 Click here to watch on YouTube]({video_url})**")
                    st.video(video_url)
                else:
                    st.error("Tutorial video link is unavailable.")
            st.markdown("</div>", unsafe_allow_html=True)

        st.markdown("</div>", unsafe_allow_html=True)

# Page Configuration
st.set_page_config(
    page_title="AI Yoga Instructor",
    page_icon="🧘",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Apply custom CSS stylesheet
apply_premium_styles()

# Global module initializations (Cached to avoid re-instantiation on rerun)
@st.cache_resource
def get_pose_detector():
    return PoseDetector()

@st.cache_resource
def get_upload_pose_detector():
    # Instantiates a highly tolerant detector specifically optimized for sketches, drawings, cartoons, and illustrations
    return PoseDetector(min_detection_confidence=0.15, min_tracking_confidence=0.15)

@st.cache_resource
def get_yoga_analyzer():
    return YogaAnalyzer()

@st.cache_resource
def get_similarity_engine():
    return PoseSimilarityEngine()

@st.cache_resource
def get_voice_coach():
    return VoiceCoach()

detector = get_pose_detector()
upload_detector = get_upload_pose_detector()
analyzer = get_yoga_analyzer()
similarity_engine = get_similarity_engine()
voice_coach = get_voice_coach()

# --- Sidebar Navigation ---
st.sidebar.markdown(
    """
    <div style="text-align: center; margin-bottom: 2rem;">
        <h2 style="color: #c084fc; font-weight: 800; margin-bottom:0;">YOGA AI</h2>
        <span style="color: #9ca3af; font-size: 0.85rem;">Computer Vision Coaching</span>
    </div>
    """,
    unsafe_allow_html=True
)

page = st.sidebar.radio(
    "NAVIGATION",
    ["Home", "Live Yoga Mode", "Upload Image Mode", "Yoga Recommendation Mode", "About Project"]
)



# Active Session state initializations
if "session_active" not in st.session_state:
    st.session_state.session_active = False
if "pose_hold_start" not in st.session_state:
    st.session_state.pose_hold_start = None
if "pose_hold_time" not in st.session_state:
    st.session_state.pose_hold_time = 0.0
if "last_milestone_voiced" not in st.session_state:
    st.session_state.last_milestone_voiced = 0

# =========================================================================
# PAGE: HOME
# =========================================================================
if page == "Home":
    render_title_section("AI YOGA INSTRUCTOR", "Hierarchical Computer Vision Yoga Coaching Companion")
    
    # Showcase banner card
    st.markdown(
        """
        <div class="glass-card" style="border-left: 5px solid #8b5cf6;">
            <h2 style="color: #c084fc; margin-top: 0;">Step Onto the Mat & Let AI Guide You</h2>
            <p style="font-size: 1.1rem; line-height: 1.6; color: #d1d5db; margin-bottom: 0;">
                This system utilizes advanced computer vision via MediaPipe and joint-angle biomechanical calculations 
                to analyze your yoga postures. Our new **Hierarchical Pose Classifier** categorizes your body posture first 
                (Standing, Sitting, Backbend, Folded, Balancing) and then scores candidate poses using temporal smoothing, 
                generating live voice corrections, a stability score, and an interactive hold timer.
            </p>
        </div>
        """,
        unsafe_allow_html=True
    )
    
    st.markdown("### Supported Yoga Postures (9 Poses Database)")
    
    # Grid of Poses
    col1, col2 = st.columns(2)
    
    poses_info = list(POSE_DATABASE.items())
    
    for idx, (pose_key, data) in enumerate(poses_info):
        target_col = col1 if idx % 2 == 0 else col2
        with target_col:
            pose_name = data["display_name"]
            desc = data["entry_guidance"]
            category = data["category"]
            
            body_html = f"""
            <span style="background: rgba(139, 92, 246, 0.25); color: #c084fc; padding: 0.15rem 0.5rem; border-radius: 4px; font-size: 0.75rem; font-weight: 600;">{category}</span>
            <p style="color: #9ca3af; font-size: 0.95rem; line-height: 1.5; margin-top: 0.5rem; margin-bottom: 0;">{desc}</p>
            """
            draw_card(pose_name, body_html)

# =========================================================================
# PAGE: LIVE YOGA MODE  (Firewall-Bypassing Websocket Camera)
# =========================================================================
elif page == "Live Yoga Mode":
    render_title_section("LIVE YOGA COACH", "Real-Time AI Pose Detection & Coaching")

    # ── Session state for live mode ──────────────────────────────────────
    if "live_active" not in st.session_state:
        st.session_state.live_active = False
    if "live_pose_hold_start" not in st.session_state:
        st.session_state.live_pose_hold_start = None
    if "live_pose_hold_time" not in st.session_state:
        st.session_state.live_pose_hold_time = 0.0
    if "live_best_accuracy" not in st.session_state:
        st.session_state.live_best_accuracy = 0.0
    if "live_total_frames" not in st.session_state:
        st.session_state.live_total_frames = 0
    if "live_last_pose" not in st.session_state:
        st.session_state.live_last_pose = "—"
    if "live_last_accuracy" not in st.session_state:
        st.session_state.live_last_accuracy = 0.0
    if "live_last_stability" not in st.session_state:
        st.session_state.live_last_stability = 0.0
    if "live_last_corrections" not in st.session_state:
        st.session_state.live_last_corrections = []
    if "live_session_logger" not in st.session_state:
        st.session_state.live_session_logger = None
    if "live_session_summary" not in st.session_state:
        st.session_state.live_session_summary = None

    # ── Layout ──────────────────────────────────────────────────────────
    col_ctrl, col_feed = st.columns([1, 2.2])

    with col_ctrl:
        st.markdown("### ⚙️ Settings")

        selected_pose = st.selectbox(
            "Target Posture",
            ["Auto-Detect"] + [data["display_name"] for data in POSE_DATABASE.values()],
            disabled=st.session_state.live_active
        )

        show_debug = st.checkbox("Show Diagnostics", value=True)

        st.markdown("---")

        # Start / Stop toggle
        if not st.session_state.live_active:
            if st.button("🎥 Start Live Session", use_container_width=True, type="primary"):
                st.session_state.live_active = True
                st.session_state.live_pose_hold_start = None
                st.session_state.live_pose_hold_time = 0.0
                st.session_state.live_best_accuracy = 0.0
                st.session_state.live_total_frames = 0
                st.session_state.live_session_logger = SessionLogger(selected_pose)
                st.session_state.live_session_summary = None
                st.rerun()
        else:
            if st.button("⏹️ Stop Session", use_container_width=True):
                st.session_state.live_active = False
                if st.session_state.live_session_logger:
                    st.session_state.live_session_summary = st.session_state.live_session_logger.save()
                    st.session_state.live_session_logger = None
                st.rerun()

        if st.session_state.live_active and st.session_state.live_session_logger:
            logger = st.session_state.live_session_logger
            
            # Live metrics sidebar
            st.markdown("#### 📊 Live Metrics")

            acc = st.session_state.live_last_accuracy
            stb = st.session_state.live_last_stability
            hold = st.session_state.live_pose_hold_time
            best = st.session_state.live_best_accuracy
            frames = st.session_state.live_total_frames
            corrections_cnt = logger.total_corrections
            
            # Format session duration
            sess_dur = int(logger.duration)
            mins, secs = divmod(sess_dur, 60)
            duration_str = f"{mins:02d}:{secs:02d}"

            acc_color = "#10b981" if acc >= 70 else "#f59e0b" if acc >= 40 else "#ef4444"
            hold_color = "#10b981" if hold > 0 else "#9ca3af"

            st.markdown(f"""
            <div class="metrics-container">
                <div class="metric-tile" style="border-color:{acc_color}; padding:0.75rem;">
                    <div class="metric-val" style="font-size:1.8rem; color:{acc_color};">{acc:.0f}%</div>
                    <div class="metric-label" style="font-size:0.7rem;">Confidence</div>
                </div>
                <div class="metric-tile" style="padding:0.75rem;">
                    <div class="metric-val" style="font-size:1.8rem; color:#818cf8;">{stb:.0f}%</div>
                    <div class="metric-label" style="font-size:0.7rem;">Stability</div>
                </div>
            </div>
            <div class="metric-tile" style="border-color:{hold_color}; margin-top:0.5rem; padding:1rem;">
                <div style="font-size:0.7rem; color:#9ca3af; text-transform:uppercase; letter-spacing:1px;">Hold Time</div>
                <div style="font-size:2rem; font-weight:800; color:{hold_color}; font-family:monospace;">{hold:.1f}s</div>
            </div>
            <div style="margin-top:0.75rem; color:#9ca3af; font-size:0.8rem; display:flex; justify-content:space-between;">
                <span>⏱️ Session: <b style="color:#e5e7eb;">{duration_str}</b></span>
                <span>🏆 Best: <b style="color:#e5e7eb;">{best:.0f}%</b></span>
                <span>🔧 Corrections: <b style="color:#e5e7eb;">{corrections_cnt}</b></span>
            </div>
            """, unsafe_allow_html=True)

            # Corrections panel
            st.markdown("#### 🧘 AI Coaching")
            if st.session_state.live_last_corrections:
                for i, corr in enumerate(st.session_state.live_last_corrections[:3]):
                    icon = "🔴" if i == 0 else "🟡" if i == 1 else "🟢"
                    st.markdown(f"{icon} {corr['message']}")
            else:
                if st.session_state.live_total_frames > 0:
                    st.success("✨ Perfect Alignment! Keep it up!")

        # Post-Session Report
        if not st.session_state.live_active and st.session_state.live_session_summary:
            summary = st.session_state.live_session_summary
            st.markdown("---")
            st.success("✅ Session Saved Successfully!")
            
            summary_html = f"""
            <div class="glass-card" style="border-color: rgba(16, 185, 129, 0.4);">
                <h4 style="margin-top:0; color:#10b981; margin-bottom:0.5rem;">Session Report</h4>
                <p style="margin-bottom:0.4rem; color: #e5e7eb;"><b>Pose:</b> {summary['pose_name']}</p>
                <p style="margin-bottom:0.4rem; color: #e5e7eb;"><b>Duration:</b> {summary['duration_seconds']}s</p>
                <p style="margin-bottom:0.4rem; color: #e5e7eb;"><b>Average Accuracy:</b> {summary['average_accuracy_pct']}%</p>
                <p style="margin-bottom:0.4rem; color: #e5e7eb;"><b>Best Accuracy:</b> {summary['best_accuracy_pct']}%</p>
                <p style="margin-bottom:0; color: #e5e7eb;"><b>Total Corrections:</b> {summary['total_corrections']}</p>
            </div>
            """
            st.markdown(summary_html, unsafe_allow_html=True)

    with col_feed:
        if not st.session_state.live_active:
            st.markdown("""
            <div class="glass-card" style="text-align:center; padding:3.5rem 2rem; border-color:rgba(139,92,246,0.3);">
                <div style="font-size:3.5rem; margin-bottom:1rem;">🧘</div>
                <div style="color:#c084fc; font-size:1.5rem; font-weight:700; margin-bottom:0.75rem;">Ready to Start</div>
                <div style="color:#9ca3af; font-size:1rem; line-height:1.8;">
                    Click <b style="color:#e5e7eb;">🎥 Start Live Session</b> to begin.<br>
                    Your browser will ask for camera permission.<br>
                    Stand back so your <b style="color:#e5e7eb;">full body is visible</b>.
                </div>
            </div>
            """, unsafe_allow_html=True)
        else:
            st.markdown("<div style='font-size:0.8rem; color:#9ca3af; text-align:center; margin-bottom: 0.5rem;'>Live Camera Active (Websocket Stream)</div>", unsafe_allow_html=True)
            st.info("Click 'Start Live Camera' below to begin streaming.")
            
            # --- Initialize our completely custom WebRTC-Bypassing Component ---
            import os
            import base64
            import mediapipe as mp
            
            # Declare the component once
            _component_func = components.declare_component(
                "custom_live_camera",
                path=os.path.join(os.path.dirname(__file__), "custom_camera")
            )
            
            # Render the component and capture the base64 string
            overlay_data = st.session_state.get('live_overlay', {})
            base64_img = _component_func(key="websocket_camera", default=None, overlay=overlay_data, height=600)

            if base64_img is not None and base64_img.startswith('data:image'):
                # Decode image from base64
                img_data = base64.b64decode(base64_img.split(',')[1])
                img_array = np.frombuffer(img_data, np.uint8)
                img_cv = cv2.imdecode(img_array, cv2.IMREAD_COLOR)

                if img_cv is not None:
                    rgb = cv2.cvtColor(img_cv, cv2.COLOR_BGR2RGB)
                    results = detector.process(rgb)

                    if results.pose_landmarks:
                        lm_list = results.pose_landmarks[0]
                        new_overlay = {"points": [], "lines": [], "hud": {}}
                        
                        # Extract landmark coordinates and connections for JS Canvas Overlay
                        POSE_CONNECTIONS = [
                            (0, 1), (1, 2), (2, 3), (3, 7), (0, 4), (4, 5), (5, 6), (6, 8), (9, 10), 
                            (11, 12), (11, 13), (13, 15), (15, 17), (15, 19), (15, 21), (17, 19), 
                            (12, 14), (14, 16), (16, 18), (16, 20), (16, 22), (18, 20), (11, 23), 
                            (12, 24), (23, 24), (23, 25), (24, 26), (25, 27), (26, 28), (27, 29), 
                            (28, 30), (29, 31), (30, 32), (27, 31), (28, 32)
                        ]
                        for connection in POSE_CONNECTIONS:
                            start_idx = connection[0]
                            end_idx = connection[1]
                            lm_start = lm_list[start_idx]
                            lm_end = lm_list[end_idx]
                            new_overlay["lines"].append([lm_start.x, lm_start.y, lm_end.x, lm_end.y])
                            
                        for lm in lm_list:
                            new_overlay["points"].append([lm.x, lm.y])
                        
                        # Check full body visibility
                        def check_vis(indices, threshold=0.5):
                            return any(getattr(lm_list[i], "visibility", 1.0) > threshold for i in indices)
                            
                        head_vis = check_vis([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]) 
                        shoulders_vis = check_vis([11, 12])
                        hips_vis = check_vis([23, 24])
                        knees_vis = check_vis([25, 26])
                        ankles_vis = check_vis([27, 28])
                        
                        if not (head_vis and shoulders_vis and hips_vis and knees_vis and ankles_vis):
                            st.warning("⚠️ Move back so your entire body is visible (head to ankles).")
                            voice_coach.alert("visibility", "Move back so your entire body is visible.", cooldown=8.0)
                            
                            new_overlay["hud"]["warning"] = "Step Back: Full Body Required"
                            st.session_state.live_overlay = new_overlay
                        else:
                            # Proceed with analysis
                            analysis = analyzer.analyze(detector, lm_list, selected_pose, is_static=True)
                            pose_key_det = analysis["detected_pose"]
                            accuracy = analysis["accuracy"]
                            stability = analysis["stability"]
                            corrections = analysis.get("corrections", [])

                            # Update session state and logger
                            st.session_state.live_total_frames += 1
                            st.session_state.live_last_accuracy = accuracy
                            st.session_state.live_last_stability = stability
                            st.session_state.live_last_corrections = corrections

                            if st.session_state.live_session_logger:
                                st.session_state.live_session_logger.record_accuracy(accuracy)
                                if corrections:
                                    st.session_state.live_session_logger.record_correction(corrections[0]["key"])

                            if accuracy > st.session_state.live_best_accuracy:
                                st.session_state.live_best_accuracy = accuracy

                            if pose_key_det != "unknown":
                                pose_display = POSE_DATABASE[pose_key_det]["display_name"]
                                st.session_state.live_last_pose = pose_display
                                voice_coach.alert(f"detected_{pose_key_det}", f"Pose detected: {pose_display}", cooldown=30.0)
                            else:
                                pose_display = "Detecting..."

                            # Voice Coach: Corrections & Reinforcement
                            if corrections:
                                main_correction = corrections[0]
                                voice_coach.alert(main_correction["key"], main_correction["message"], cooldown=8.0)
                            else:
                                if accuracy >= 80.0:
                                    voice_coach.alert("great_posture", "Great posture. Excellent balance.", cooldown=15.0)

                            # Hold timer
                            if accuracy >= 75.0:
                                if st.session_state.live_pose_hold_start is None:
                                    st.session_state.live_pose_hold_start = time.monotonic()
                                st.session_state.live_pose_hold_time = time.monotonic() - st.session_state.live_pose_hold_start
                                
                                held_sec = int(st.session_state.live_pose_hold_time)
                                if held_sec == 5:
                                    voice_coach.alert("hold_5", "Good, hold it there.", cooldown=30.0)
                                elif held_sec == 15:
                                    voice_coach.alert("hold_15", "Excellent, keep holding.", cooldown=30.0)
                                elif held_sec == 30:
                                    voice_coach.alert("hold_30", "Amazing balance, 30 seconds reached.", cooldown=60.0)
                            else:
                                if st.session_state.live_pose_hold_start is not None:
                                    st.session_state.live_pose_hold_start = time.monotonic() - st.session_state.live_pose_hold_time

                            new_overlay["hud"]["pose"] = pose_display
                            new_overlay["hud"]["confidence"] = f"{int(accuracy)}%"
                            new_overlay["hud"]["stability"] = f"{int(stability)}%"
                            new_overlay["hud"]["hold"] = f"{st.session_state.live_pose_hold_time:.1f}s"
                            st.session_state.live_overlay = new_overlay

                            if show_debug:
                                candidate_scores = analysis.get("candidate_scores", {})
                                if candidate_scores:
                                    st.markdown("**Top Candidate Poses:**")
                                    sorted_c = sorted(candidate_scores.items(), key=lambda x: x[1], reverse=True)
                                    for pname, score in sorted_c[:4]:
                                        bar_color = "#10b981" if score >= 70 else "#f59e0b" if score >= 40 else "#ef4444"
                                        st.markdown(f"""
                                        <div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:4px;">
                                            <span style="color:#e5e7eb;font-size:0.82rem;">{pname}</span>
                                            <div style="display:flex;align-items:center;gap:8px;">
                                                <div style="width:90px;background:rgba(255,255,255,0.07);height:6px;border-radius:3px;">
                                                    <div style="background:{bar_color};width:{min(score,100)}%;height:6px;border-radius:3px;"></div>
                                                </div>
                                                <b style="color:{bar_color};font-size:0.82rem;min-width:36px;">{score:.0f}%</b>
                                            </div>
                                        </div>
                                        """, unsafe_allow_html=True)
                    else:
                        st.image(cv2.cvtColor(img_cv, cv2.COLOR_BGR2RGB), use_container_width=True)
                        st.warning("⚠️ No pose detected — stand back so your full body is visible.")

# =========================================================================
# PAGE: UPLOAD IMAGE MODE
# =========================================================================
elif page == "Upload Image Mode":
    render_title_section("IMAGE ANALYZER", "Enhanced AI Diagnostics for Static Posture Analysis")
    
    st.markdown(
        """
        <div class="glass-card" style="margin-bottom: 2.0rem;">
            <h4 style="margin-top: 0; color: #818cf8; margin-bottom: 0.5rem;">Upload Guidelines</h4>
            <ul style="color: #9ca3af; margin-bottom: 0; padding-left: 1.2rem; line-height: 1.5;">
                <li>Supported formats: JPG, JPEG, PNG</li>
                <li>Ensure the full body is visible in the frame</li>
                <li>Good lighting helps with pose detection accuracy</li>
                <li>The system uses multi-stage preprocessing to enhance low-quality images</li>
            </ul>
        </div>
        """,
        unsafe_allow_html=True
    )
    
    uploaded_file = st.file_uploader("Choose an image...", type=["jpg", "jpeg", "png"])

    if uploaded_file:
        try:
            # Process uploaded image
            img_cv = ImagePreprocessor.process_to_cv2(uploaded_file)
            if img_cv is not None:
                col1, col2 = st.columns([1, 1])
                with col1:
                    st.markdown("### Source Image & Detection")
                    
                    # Use enhanced preprocessing pipeline for uploaded images
                    try:
                        # Run enhanced preprocessing pipeline directly from memory
                        success, processed_img, stage_name, results, original_resized = ImagePreprocessor.run_detection_pipeline(img_cv, upload_detector)
                        
                        if success and results and results.pose_landmarks:
                            annotated = processed_img.copy()
                            upload_detector.draw_landmarks(annotated, results.pose_landmarks[0])
                            st.image(cv2.cvtColor(annotated, cv2.COLOR_BGR2RGB), use_container_width=True)
                            st.caption(f"✓ Pose detected on {stage_name}")
                        else:
                            # Show original image if detection failed
                            st.image(cv2.cvtColor(img_cv, cv2.COLOR_BGR2RGB), use_container_width=True)
                            st.warning("⚠ No pose skeleton detected in any preprocessing stage.")
                    except Exception as e:
                        st.error(f"Preprocessing error: {str(e)}")
                        st.image(cv2.cvtColor(img_cv, cv2.COLOR_BGR2RGB), use_container_width=True)
                
                with col2:
                    st.markdown("### Diagnostic Metrics")
                    
                    # Use robust results if successful, else fallback to basic
                    target_results = results if (success and results and hasattr(results, 'pose_landmarks') and results.pose_landmarks) else None
                    if not target_results:
                        target_results = upload_detector.process(cv2.cvtColor(img_cv, cv2.COLOR_BGR2RGB))
                    
                    if target_results and target_results.pose_landmarks:
                        try:
                            # 1. Landmark Quality & Visibility Check
                            lm_list = target_results.pose_landmarks[0]
                            
                            vis_scores = []
                            core_indices = [11, 12, 23, 24, 25, 26, 27, 28]  # shoulders, hips, knees, ankles
                            for idx in core_indices:
                                try:
                                    lm = lm_list[idx]
                                    vis_scores.append(getattr(lm, "visibility", 1.0))
                                except Exception:
                                    vis_scores.append(0.5)
                            
                            avg_visibility = sum(vis_scores) / len(vis_scores) if vis_scores else 0
                            
                            if avg_visibility < 0.30:
                                st.error("Image quality insufficient for accurate pose detection")
                                st.info(f"Landmark visibility score: {avg_visibility:.2f} (Minimum required: 0.30)")
                                st.write("Please upload a clearer image where the full body is visible.")
                            else:
                                # 2. Extract features using existing primitives
                                c = analyzer._extract_coords(upload_detector, lm_list)
                                ac = analyzer._build_angle_cache(c)
                                o = analyzer._compute_orientation(c, ac)
                                
                                # 3. Category-First Classification
                                cat_result = analyzer.classify_category(c, ac, o)
                                detected_category = cat_result[0]
                                cat_conf = cat_result[1] if len(cat_result) > 1 else 0.0
                                cat_reason = cat_result[2] if len(cat_result) > 2 else ""
                                
                                # 4. Dataset-Assisted Pose Similarity Engine
                                sim_result = similarity_engine.evaluate_image(detected_category, c, ac, o)
                                if isinstance(sim_result, tuple) and len(sim_result) == 2:
                                    candidate_scores, candidate_details = sim_result
                                else:
                                    candidate_scores = sim_result if isinstance(sim_result, dict) else {}
                                    candidate_details = {}
                                
                                # Sort candidates by confidence
                                sorted_candidates = sorted(candidate_scores.items(), key=lambda x: x[1], reverse=True)
                                
                                # Determine best pose
                                best_pose = "unknown"
                                best_score = 0.0
                                if sorted_candidates:
                                    best_pose, best_score = sorted_candidates[0]
                                    
                                is_low_confidence = best_score < 55.0
                                
                                # 5. Interactive UI Display
                                col_m1, col_m2 = st.columns(2)
                                with col_m1:
                                    st.metric("Top Confidence", f"{best_score:.1f}%")
                                with col_m2:
                                    st.metric("Visibility Score", f"{avg_visibility * 100:.1f}%")
                                
                                if is_low_confidence:
                                    st.warning("⚠ Pose Uncertain — confidence below threshold")
                                    st.info("**Detected Pose:** Pose Uncertain")
                                else:
                                    display = best_pose.replace('_', ' ').title()
                                    st.success(f"**Detected Pose:** {display}")
                                
                                st.write(f"**Body Category:** {detected_category} (conf: {cat_conf:.0f}%)")
                                if cat_reason:
                                    st.caption(f"Reason: {cat_reason}")
                                
                                # Debug Panel: Top 3 Candidate Poses
                                if sorted_candidates:
                                    st.markdown("**✅ Top 3 Candidate Poses:**")
                                    for pose_name, score in sorted_candidates[:3]:
                                        display_name = pose_name.replace('_', ' ').title()
                                        st.write(f"- {display_name} → {score:.1f}%")
                                
                                # Debug Panel: Matched & Failed Features
                                if best_pose != "unknown" and candidate_details:
                                    with st.expander(f"🔍 Feature Breakdown: {best_pose.replace('_', ' ').title()}"):
                                        details = candidate_details.get(best_pose, {})
                                        if details.get("matched"):
                                            st.markdown("**Matched Features:**")
                                            for m in details.get("matched", []):
                                                st.write(f"🟢 {m}")
                                        if details.get("failed"):
                                            st.markdown("**Failed Features:**")
                                            for f_item in details.get("failed", []):
                                                st.write(f"🔴 {f_item}")
                                                
                                # Debug Panel: Orientation Metrics
                                with st.expander("📐 Body Orientation Metrics"):
                                    display_o = {k: round(v, 4) if isinstance(v, float) else v for k, v in o.items()}
                                    st.json(display_o)
                                
                                with st.expander("🦴 Joint Angles"):
                                    display_ac = {}
                                    for k, v in ac.items():
                                        if isinstance(v, float):
                                            display_ac[k] = round(v, 2)
                                        elif isinstance(v, tuple):
                                            display_ac[k] = [round(x, 4) for x in v]
                                        else:
                                            display_ac[k] = str(v)
                                    st.json(display_ac)
                        except Exception as e:
                            import traceback
                            st.warning(f"Analysis error: {str(e)}")
                            st.code(traceback.format_exc(), language="text")
                    else:
                        st.info("No pose skeleton detected. Try:\n- Better lighting\n- Full body in frame\n- Higher quality image")
            else:
                st.error("Failed to decode image. Try:\n- Different format (JPG/PNG)\n- Smaller file size\n- Standard resolution")
        except Exception as e:
            st.error(f"Error processing upload: {str(e)}")
            st.info("Please try uploading a different image or check the file format.")
    else:
        st.info("Upload a clear image to begin hierarchical posture classification.")

# =========================================================================
# PAGE: YOGA RECOMMENDATION MODE
# =========================================================================
elif page == "Yoga Recommendation Mode":
    # Netflix-style card CSS for recommendation page
    st.markdown(
        """
        <style>
        .rec-title {
            font-size: 2.8rem;
            font-weight: 800;
            background: linear-gradient(90deg, #38bdf8 0%, #a78bfa 50%, #f472b6 100%);
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
            text-align: center;
            margin-bottom: 0.15rem;
        }
        .rec-subtitle {
            text-align: center;
            color: #9ca3af;
            font-size: 1.1rem;
            margin-bottom: 1.5rem;
        }
        .video-card {
            background: rgba(15, 23, 42, 0.75);
            border: 1px solid rgba(56, 189, 248, 0.18);
            border-radius: 16px;
            overflow: hidden;
            margin-bottom: 1.5rem;
            transition: border-color 0.3s ease, box-shadow 0.3s ease;
        }
        .video-card:hover {
            border-color: rgba(56, 189, 248, 0.45);
            box-shadow: 0 0 24px rgba(56, 189, 248, 0.12);
        }
        .video-card-body {
            padding: 1rem 1.1rem 1.1rem 1.1rem;
        }
        .video-card-title-row {
            display: flex;
            justify-content: space-between;
            align-items: flex-start;
            margin-bottom: 0.45rem;
            gap: 0.5rem;
        }
        .video-card-title {
            font-size: 1rem;
            font-weight: 700;
            color: #e2e8f0;
            line-height: 1.35;
        }
        .badge {
            display: inline-block;
            padding: 0.15rem 0.55rem;
            border-radius: 6px;
            font-size: 0.7rem;
            font-weight: 700;
            white-space: nowrap;
            flex-shrink: 0;
        }
        .badge-beginner { background: rgba(16, 185, 129, 0.18); color: #34d399; border: 1px solid rgba(16, 185, 129, 0.35); }
        .badge-intermediate { background: rgba(245, 158, 11, 0.18); color: #fbbf24; border: 1px solid rgba(245, 158, 11, 0.35); }
        .badge-advanced { background: rgba(239, 68, 68, 0.18); color: #f87171; border: 1px solid rgba(239, 68, 68, 0.35); }
        .video-card-desc {
            font-size: 0.85rem;
            color: #94a3b8;
            line-height: 1.45;
            margin-bottom: 0.6rem;
        }
        .video-card-benefits {
            font-size: 0.78rem;
            color: #38bdf8;
            font-weight: 600;
            margin-bottom: 0.75rem;
        }
        .video-card-tags {
            display: flex;
            flex-wrap: wrap;
            gap: 0.4rem;
            align-items: center;
        }
        .tag-pill {
            display: inline-block;
            padding: 0.18rem 0.55rem;
            border-radius: 999px;
            font-size: 0.68rem;
            font-weight: 600;
            background: rgba(255, 255, 255, 0.06);
            color: #9ca3af;
            border: 1px solid rgba(255, 255, 255, 0.08);
        }
        .watch-btn {
            display: inline-flex;
            align-items: center;
            gap: 0.3rem;
            padding: 0.2rem 0.6rem;
            border-radius: 999px;
            font-size: 0.7rem;
            font-weight: 700;
            background: rgba(56, 189, 248, 0.15);
            color: #38bdf8;
            border: 1px solid rgba(56, 189, 248, 0.3);
            text-decoration: none;
            cursor: pointer;
        }
        </style>
        """,
        unsafe_allow_html=True
    )

    # --- Page Header ---
    st.markdown('<div class="rec-title">Yoga Search & Discovery</div>', unsafe_allow_html=True)
    st.markdown('<div class="rec-subtitle">Find yoga tutorials for wellness and fitness goals</div>', unsafe_allow_html=True)

    # --- Search Bar ---
    if "rec_search_input" not in st.session_state:
        st.session_state.rec_search_input = ""

    col_input, col_btn = st.columns([4, 1])
    with col_input:
        search_query = st.text_input(
            "Search your wellness goal",
            placeholder="e.g. stress relief, back pain, weight loss, flexibility...",
            label_visibility="collapsed",
            key="rec_search_input"
        )
    with col_btn:
        st.button("🔍 Search", use_container_width=True)

    # --- Quick Suggestion Chips ---
    st.markdown("**💡 Quick Suggestions:**")
    suggestions = [
        ("Back Pain", "back pain"),
        ("Stress Relief", "stress relief"),
        ("Flexibility", "flexibility"),
        ("Weight Loss", "weight loss"),
        ("Neck Pain", "neck pain"),
        ("Beginner", "beginner yoga"),
    ]
    
    def set_search_query(val):
        st.session_state.rec_search_input = val

    chip_cols = st.columns(len(suggestions))
    for idx, (label, search_val) in enumerate(suggestions):
        with chip_cols[idx]:
            st.button(label, key=f"suggest_{idx}", on_click=set_search_query, args=(search_val,), use_container_width=True)

    st.divider()

    # --- Results Section ---
    query_text = search_query.strip()

    if query_text:
        st.markdown(f"Results for '*{query_text}*'  &nbsp; **+ AI**", unsafe_allow_html=True)
        st.markdown("")

        videos = YogaRecommendationEngine.get_videos_for_query(query_text)

        if videos:
            # Render in rows of 3 — Netflix-style cards with embedded YouTube
            for i in range(0, len(videos), 3):
                cols = st.columns(3, gap="medium")
                for j in range(3):
                    if i + j < len(videos):
                        video = videos[i + j]
                        video_url = video["url"]
                        parsed_id = YogaRecommendationEngine.extract_youtube_id(video_url)

                        # Difficulty badge class
                        diff = video.get("difficulty", "Beginner")
                        if diff == "Beginner":
                            badge_class = "badge-beginner"
                        elif diff == "Intermediate":
                            badge_class = "badge-intermediate"
                        else:
                            badge_class = "badge-advanced"

                        # Build tag pills HTML
                        tags = video.get("tags", [])
                        duration = video.get("duration", "")
                        tag_pills = ""
                        if tags:
                            for t in tags:
                                tag_pills += f'<span class="tag-pill">{t}</span>'
                        if duration:
                            tag_pills += f'<span class="tag-pill">{duration}</span>'

                        # Benefits text
                        benefits = video.get("benefits", [])
                        benefits_text = " · ".join(benefits) if benefits else ""

                        with cols[j]:
                            # Embedded YouTube player via components.html (bypasses Streamlit's iframe sanitizer)
                            yt_embed_html = f'''
                            <div style="position:relative;padding-bottom:56.25%;height:0;overflow:hidden;border-radius:8px 8px 0 0;">
                                <iframe src="https://www.youtube.com/embed/{parsed_id}"
                                    style="position:absolute;top:0;left:0;width:100%;height:100%;border:none;"
                                    allow="accelerometer;autoplay;clipboard-write;encrypted-media;gyroscope;picture-in-picture"
                                    allowfullscreen></iframe>
                            </div>
                            '''
                            components.html(yt_embed_html, height=200)

                            # Card body with title, badge, description, benefits, tags
                            card_html = f"""
                            <div class="video-card-body">
                                <div class="video-card-title-row">
                                    <span class="video-card-title">{video['title']}</span>
                                    <span class="badge {badge_class}">{diff}</span>
                                </div>
                                <div class="video-card-desc">{video['description']}</div>
                                <div class="video-card-benefits">{benefits_text}</div>
                                <div class="video-card-tags">
                                    {tag_pills}
                                    <a href="{video_url}" target="_blank" class="watch-btn">▶ Watch</a>
                                </div>
                            </div>
                            """
                            st.markdown(card_html, unsafe_allow_html=True)
        else:
            st.warning(f'No tutorials found for "{query_text}". Try one of the quick suggestions above!')
    else:
        # Empty state
        st.markdown("---")
        st.markdown(
            """
            ### 🧘 Discovery Hub Active

            Type any wellness goal in the search bar above to find targeted yoga tutorials.

            **Try searching for:**
            - *"back pain"* — stretches for spinal relief
            - *"stress relief"* — calming breathing flows
            - *"weight loss"* — power vinyasa flows
            - *"flexibility"* — deep hip and hamstring stretches
            - *"beginner yoga"* — gentle starter routines
            """
        )


# =========================================================================
# PAGE: ABOUT PROJECT
# =========================================================================
elif page == "About Project":
    render_title_section("PROJECT METRICS", "Architecture & Technical Specifications")

    col_stack, col_arch = st.columns([1, 1])

    with col_stack:
        st.markdown("### System Architecture")
        
        arch_details = """
        <p style="color:#d1d5db; line-height:1.6; font-size:0.95rem;">
            This system runs entirely locally on Windows to offer real-time computer vision training without sending your camera feed to external cloud servers.
        </p>
        <ul style="color:#9ca3af; font-size:0.95rem; line-height:1.6; padding-left: 1.2rem;">
            <li><b>Hierarchical Category Classifier:</b> Groups body layouts into high-level Categories first before analyzing candidate poses, solving splay conflicts.</li>
            <li><b>Computer Vision Model:</b> MediaPipe Pose Landmarker utilizing full-body landmarks (33 keypoints in 3D).</li>
            <li><b>Biomechanical Features:</b> Angle calculators utilizing vector geometry, slopes, splay lines (NumPy).</li>
            <li><b>Pose locking & Temporal Smoothing:</b> Lock mechanism retaining stable pose classification and majority vote rolling frame buffers preventing pose flickering.</li>
            <li><b>Visibility Warnings:</b> Pauses estimation if crucial joints exit the camera frame boundary.</li>
            <li><b>Vocal Guide:</b> Thread-safe offline pyttsx3, prioritizing single high-priority corrections.</li>
        </ul>
        """
        draw_card("Local Computations", arch_details)

    with col_arch:
        st.markdown("### Tech Stack Used")
        
        stack_html = """
        <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 1rem; font-size: 0.95rem;">
            <div style="background: rgba(255, 255, 255, 0.03); border: 1px solid rgba(255, 255, 255, 0.05); padding: 0.75rem; border-radius: 8px;">
                <b style="color: #c084fc;">Streamlit</b><br>
                <span style="color: #9ca3af;">Frontend Dashboard</span>
            </div>
            <div style="background: rgba(255, 255, 255, 0.03); border: 1px solid rgba(255, 255, 255, 0.05); padding: 0.75rem; border-radius: 8px;">
                <b style="color: #c084fc;">MediaPipe</b><br>
                <span style="color: #9ca3af;">Full Skeleton Extraction</span>
            </div>
            <div style="background: rgba(255, 255, 255, 0.03); border: 1px solid rgba(255, 255, 255, 0.05); padding: 0.75rem; border-radius: 8px;">
                <b style="color: #c084fc;">OpenCV</b><br>
                <span style="color: #9ca3af;">Webcam Capture & Drawing</span>
            </div>
            <div style="background: rgba(255, 255, 255, 0.03); border: 1px solid rgba(255, 255, 255, 0.05); padding: 0.75rem; border-radius: 8px;">
                <b style="color: #c084fc;">pyttsx3</b><br>
                <span style="color: #9ca3af;">Offline Threaded TTS</span>
            </div>
            <div style="background: rgba(255, 255, 255, 0.03); border: 1px solid rgba(255, 255, 255, 0.05); padding: 0.75rem; border-radius: 8px;">
                <b style="color: #c084fc;">NumPy</b><br>
                <span style="color: #9ca3af;">Vector Geometry Calculations</span>
            </div>
            <div style="background: rgba(255, 255, 255, 0.03); border: 1px solid rgba(255, 255, 255, 0.05); padding: 0.75rem; border-radius: 8px;">
                <b style="color: #c084fc;">JSON Logs</b><br>
                <span style="color: #9ca3af;">Session Tracker Data</span>
            </div>
        </div>
        """
        draw_card("Developer Specifications", stack_html)

# Add dynamic project footer
st.sidebar.markdown(
    """
    <div style="position: fixed; bottom: 1rem; width: 14%; text-align: center; border-top: 1px solid rgba(255,255,255,0.05); padding-top:0.5rem;">
        <span style="color:#4b5563; font-size:0.75rem;">AI Yoga Coach v2.0.0</span>
    </div>
    """,
    unsafe_allow_html=True
)
