"""
AI Yoga Instructor using Computer Vision - Main App Entry Point.
Streamlit application incorporating real-time hierarchical pose tracking, joint angle math,
offline audio coaching, candidate confidence leaderboards, pose hold timers, and wellness recommendations.
"""

import os
import re
import cv2
import time
import numpy as np
import streamlit as st
from PIL import Image
from pathlib import Path

# Core imports
from yoga_config import CAMERA_INDEX, POSE_DATABASE
from pose_detector import PoseDetector
from yoga_analyzer import YogaAnalyzer
from voice_coach import VoiceCoach
from recommendation_engine import YogaRecommendationEngine
from session_logger import SessionLogger
from utils.ui_components import apply_premium_styles, render_title_section, draw_card
from utils.image_preprocessor import ImagePreprocessor
from utils.pose_statistics import load_statistics

# Initialize directories
os.makedirs("uploads", exist_ok=True)
os.makedirs("assets", exist_ok=True)
os.makedirs("data", exist_ok=True)

# ---------------------------------------------------------------------------
# Load dataset-derived pose statistics (if available)
# ---------------------------------------------------------------------------
_STATS_PATH = Path(__file__).parent / "data" / "pose_stats.json"


@st.cache_data
def load_pose_stats():
    """Load pose_stats.json generated by build_pose_database.py."""
    stats = load_statistics(_STATS_PATH)
    if stats:
        print(f"[APP] Loaded dataset pose statistics from {_STATS_PATH}")
    return stats


def get_class_angle_distribution(class_name: str) -> dict | None:
    """
    Return per-joint angle statistics for a given class.

    Returns dict like:
        {"left_knee": {"mean": 95.2, "std": 8.1, "min": 72.0, "max": 120.0}, ...}
    or None if stats are not available for that class.
    """
    stats = load_pose_stats()
    if not stats:
        return None
    cls_data = stats.get("classes", {}).get(class_name)
    if not cls_data:
        return None
    return cls_data.get("joints")


def get_dataset_threshold(pose_key: str) -> float | None:
    """
    Return the dataset-derived confidence threshold for a pose, or None
    if no dataset stats are available for this pose.
    """
    stats = load_pose_stats()
    if not stats:
        return None
    cls_data = stats.get("classes", {}).get(pose_key)
    if cls_data:
        return cls_data.get("confidence_threshold")
    return None


def normalize_youtube_url(video_value: str | None) -> str | None:
    """Normalize YouTube URLs so the player works with watch, embed, and youtu.be links."""
    if not video_value:
        return None

    value = str(video_value).strip()
    if not value:
        return None

    if value.startswith(("http://", "https://")):
        if "youtu.be/" in value:
            video_id = value.split("youtu.be/")[-1].split("?", 1)[0].split("&", 1)[0]
            return f"https://www.youtube.com/watch?v={video_id}"
        if "youtube.com/embed/" in value:
            video_id = value.split("youtube.com/embed/")[-1].split("?", 1)[0].split("&", 1)[0]
            return f"https://www.youtube.com/watch?v={video_id}"
        if "youtube.com/watch?v=" in value:
            return value
        if "youtube.com/shorts/" in value:
            video_id = value.split("youtube.com/shorts/")[-1].split("?", 1)[0].split("&", 1)[0]
            return f"https://www.youtube.com/watch?v={video_id}"
        return value

    if re.fullmatch(r"[A-Za-z0-9_-]{11}", value):
        return f"https://www.youtube.com/watch?v={value}"

    return None


def render_pose_card(pose: dict) -> None:
    """Render a clean, modern pose recommendation card with lazy tutorial playback."""
    video_url = normalize_youtube_url(pose.get("youtube_id"))

    with st.expander(f"🧘 {pose['name']}  •  {pose['difficulty']}", expanded=False):
        st.markdown("<div class='glass-card recommendation-card'>", unsafe_allow_html=True)

        left, right = st.columns([1.05, 0.95], gap="large")
        with left:
            image_path = pose.get("image_path") or "assets/recommendation/mountain.svg"
            st.image(image_path, use_column_width=True, caption=pose.get("category", "Wellness"))
            st.write(pose.get("description", "A supportive yoga posture for your wellness goal."))
            st.markdown("<div class='mini-section'>", unsafe_allow_html=True)
            st.markdown("<h5 class='mini-title'>Why it helps</h5>", unsafe_allow_html=True)
            for benefit in pose.get("benefits", []):
                st.markdown(f"- ✨ {benefit}", unsafe_allow_html=True)
            st.markdown("</div>", unsafe_allow_html=True)

        with right:
            st.markdown("<div class='mini-section'>", unsafe_allow_html=True)
            st.markdown("<h5 class='mini-title'>Step-by-step guidance</h5>", unsafe_allow_html=True)
            for step in pose.get("steps", []):
                st.markdown(f"1. {step}", unsafe_allow_html=True)
            st.markdown("</div>", unsafe_allow_html=True)

            st.markdown("<div class='mini-section'>", unsafe_allow_html=True)
            st.markdown("<h5 class='mini-title'>Video Tutorial</h5>", unsafe_allow_html=True)
            with st.expander("▶ Open Video Player", expanded=False):
                if video_url:
                    st.markdown(f"**[🔗 Click here to watch on YouTube]({video_url})**")
                    st.video(video_url)
                else:
                    st.error("Tutorial video link is unavailable.")
            st.markdown("</div>", unsafe_allow_html=True)

        st.markdown("</div>", unsafe_allow_html=True)

# Page Configuration
st.set_page_config(
    page_title="AI Yoga Instructor",
    page_icon="🧘",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Apply custom CSS stylesheet
apply_premium_styles()

# Global module initializations (Cached to avoid re-instantiation on rerun)
@st.cache_resource
def get_pose_detector():
    return PoseDetector()

@st.cache_resource
def get_upload_pose_detector():
    # Instantiates a highly tolerant detector specifically optimized for sketches, drawings, cartoons, and illustrations
    return PoseDetector(min_detection_confidence=0.15, min_tracking_confidence=0.15)

@st.cache_resource
def get_yoga_analyzer():
    return YogaAnalyzer()

@st.cache_resource
def get_voice_coach():
    return VoiceCoach()

detector = get_pose_detector()
upload_detector = get_upload_pose_detector()
analyzer = get_yoga_analyzer()
voice_coach = get_voice_coach()

# --- Sidebar Navigation ---
st.sidebar.markdown(
    """
    <div style="text-align: center; margin-bottom: 2rem;">
        <h2 style="color: #c084fc; font-weight: 800; margin-bottom:0;">YOGA AI</h2>
        <span style="color: #9ca3af; font-size: 0.85rem;">Computer Vision Coaching</span>
    </div>
    """,
    unsafe_allow_html=True
)

page = st.sidebar.radio(
    "NAVIGATION",
    ["Home", "Live Yoga Mode", "Upload Image Mode", "Yoga Recommendation Mode", "About Project"]
)



# Active Session state initializations
if "session_active" not in st.session_state:
    st.session_state.session_active = False
if "pose_hold_start" not in st.session_state:
    st.session_state.pose_hold_start = None
if "pose_hold_time" not in st.session_state:
    st.session_state.pose_hold_time = 0.0
if "last_milestone_voiced" not in st.session_state:
    st.session_state.last_milestone_voiced = 0

# =========================================================================
# PAGE: HOME
# =========================================================================
if page == "Home":
    render_title_section("AI YOGA INSTRUCTOR", "Hierarchical Computer Vision Yoga Coaching Companion")
    
    # Showcase banner card
    st.markdown(
        """
        <div class="glass-card" style="border-left: 5px solid #8b5cf6;">
            <h2 style="color: #c084fc; margin-top: 0;">Step Onto the Mat & Let AI Guide You</h2>
            <p style="font-size: 1.1rem; line-height: 1.6; color: #d1d5db; margin-bottom: 0;">
                This system utilizes advanced computer vision via MediaPipe and joint-angle biomechanical calculations 
                to analyze your yoga postures. Our new **Hierarchical Pose Classifier** categorizes your body posture first 
                (Standing, Sitting, Backbend, Folded, Balancing) and then scores candidate poses using temporal smoothing, 
                generating live voice corrections, a stability score, and an interactive hold timer.
            </p>
        </div>
        """,
        unsafe_allow_html=True
    )
    
    st.markdown("### Supported Yoga Postures (9 Poses Database)")
    
    # Grid of Poses
    col1, col2 = st.columns(2)
    
    poses_info = list(POSE_DATABASE.items())
    
    for idx, (pose_key, data) in enumerate(poses_info):
        target_col = col1 if idx % 2 == 0 else col2
        with target_col:
            pose_name = data["display_name"]
            desc = data["entry_guidance"]
            category = data["category"]
            
            body_html = f"""
            <span style="background: rgba(139, 92, 246, 0.25); color: #c084fc; padding: 0.15rem 0.5rem; border-radius: 4px; font-size: 0.75rem; font-weight: 600;">{category}</span>
            <p style="color: #9ca3af; font-size: 0.95rem; line-height: 1.5; margin-top: 0.5rem; margin-bottom: 0;">{desc}</p>
            """
            draw_card(pose_name, body_html)

# =========================================================================
# PAGE: LIVE YOGA MODE
# =========================================================================
elif page == "Live Yoga Mode":
    render_title_section("LIVE YOGA COACH", "Interactive Webcam Pose Tracker with Vocal Corrections & Timers")

    # Instructions Card
    st.markdown(
        """
        <div class="glass-card" style="margin-bottom: 2.0rem;">
            <h4 style="margin-top: 0; color: #818cf8; margin-bottom: 0.5rem;">Setup Guidelines</h4>
            <ul style="color: #9ca3af; margin-bottom: 0; padding-left: 1.2rem; line-height: 1.5;">
                <li>Place your webcam at torso height to capture your entire body standing, sitting, or lying down.</li>
                <li><b>Temporal Smoothing & Auto-Detect:</b> The system filters out flickering noise. Maintain a pose for a few frames to establish a stable lock.</li>
                <li>Hold accuracy above <b>70%</b> to trigger the posture hold timer!</li>
            </ul>
        </div>
        """,
        unsafe_allow_html=True
    )

    # Controller Column Setup
    col_ctrl, col_feed = st.columns([1, 2.2])

    with col_ctrl:
        st.markdown("### Settings & Controls")
        
        # Mode Selection
        selected_pose = st.selectbox(
            "Select Target Posture",
            ["Auto-Detect"] + [data["display_name"] for data in POSE_DATABASE.values()]
        )

        # Cooldown selector for voice
        voice_cooldown = st.slider("Voice Feedback Cooldown (sec)", 3.0, 15.0, 6.0, step=0.5)

        # Debug Panel checkbox toggle
        show_debug = st.checkbox("Show AI Diagnostics Overlay", value=True)

        # Toggle Button
        if not st.session_state.session_active:
            start_btn = st.button("Start AI Coaching")
            if start_btn:
                st.session_state.session_active = True
                st.session_state.session_logger = SessionLogger(
                    active_pose=selected_pose
                )
                st.session_state.pose_hold_start = None
                st.session_state.pose_hold_time = 0.0
                st.session_state.last_milestone_voiced = 0
                st.rerun()
        else:
            # Place in a custom stop-btn container for styling
            st.markdown('<div class="stop-btn">', unsafe_allow_html=True)
            stop_btn = st.button("Stop AI Coaching")
            st.markdown('</div>', unsafe_allow_html=True)
            
            if stop_btn:
                st.session_state.session_active = False
                # Save session metrics
                if "session_logger" in st.session_state:
                    summary = st.session_state.session_logger.save()
                    st.session_state.last_session_summary = summary
                st.rerun()

        # Render Active Metrics if session is running
        if st.session_state.session_active and "session_logger" in st.session_state:
            logger = st.session_state.session_logger
            st.markdown("---")
            
            # Dashboard grid
            metrics_html = f"""
            <div class="metrics-container">
                <div class="metric-tile" style="padding:0.75rem;">
                    <div class="metric-val" style="font-size:1.8rem;">{logger.total_corrections}</div>
                    <div class="metric-label" style="font-size:0.7rem;">Corrections</div>
                </div>
                <div class="metric-tile" style="padding:0.75rem;">
                    <div class="metric-val" style="font-size:1.8rem;">{logger.best_accuracy:.0f}%</div>
                    <div class="metric-label" style="font-size:0.7rem;">Best Acc</div>
                </div>
            </div>
            """
            st.markdown(metrics_html, unsafe_allow_html=True)

            # Hold Timer Dashboard Tile
            timer_color = "#10b981" if st.session_state.pose_hold_time > 0 else "#9ca3af"
            timer_html = f"""
            <div class="metric-tile" style="border-color: {timer_color}; margin-top: 0.5rem; padding: 1.0rem;">
                <div style="font-size: 0.75rem; color: #9ca3af; text-transform: uppercase; letter-spacing:1px; margin-bottom:0.25rem;">Hold Duration</div>
                <div style="font-size: 2.2rem; font-weight: 800; color: {timer_color}; font-family: monospace;">{st.session_state.pose_hold_time:.1f}s</div>
            </div>
            """
            st.markdown(timer_html, unsafe_allow_html=True)

        # Show summary if last session just finished
        if not st.session_state.session_active and "last_session_summary" in st.session_state:
            summary = st.session_state.last_session_summary
            st.markdown("---")
            st.success("Session finished successfully!")
            
            summary_html = f"""
            <div class="glass-card" style="border-color: rgba(16, 185, 129, 0.4);">
                <h4 style="margin-top:0; color:#10b981; margin-bottom:0.5rem;">Session Saved Successfully</h4>
                <p style="margin-bottom:0.4rem; color: #e5e7eb;"><b>Pose:</b> {summary['pose_name']}</p>
                <p style="margin-bottom:0.4rem; color: #e5e7eb;"><b>Duration:</b> {summary['duration_seconds']}s</p>
                <p style="margin-bottom:0.4rem; color: #e5e7eb;"><b>Average Accuracy:</b> {summary['average_accuracy_pct']}%</p>
                <p style="margin-bottom:0.4rem; color: #e5e7eb;"><b>Best Accuracy:</b> {summary['best_accuracy_pct']}%</p>
                <p style="margin-bottom:0; color: #e5e7eb;"><b>Total Corrections:</b> {summary['total_corrections']}</p>
            </div>
            """
            st.markdown(summary_html, unsafe_allow_html=True)

    with col_feed:
        st.markdown("### Webcam Feed")
        frame_placeholder = st.empty()
        
        # Real-time indicators overlay
        indicators_placeholder = st.empty()
        
        # Candidate pose scoring bar chart
        chart_placeholder = st.empty()

        if st.session_state.session_active:
            cap = cv2.VideoCapture(CAMERA_INDEX)
            cap.set(cv2.CAP_PROP_FRAME_WIDTH, 1280)
            cap.set(cv2.CAP_PROP_FRAME_HEIGHT, 720)

            if not cap.isOpened():
                st.error("Error: Could not access the webcam. Check connection or camera index.")
                st.session_state.session_active = False
            else:
                logger = st.session_state.session_logger
                prev_time = time.monotonic()
                fps = 30.0
                frame_count = 0

                try:
                    while cap.isOpened() and st.session_state.session_active:
                        ret, frame = cap.read()
                        if not ret:
                            st.warning("Failed to grab camera frame. Retrying...")
                            continue
                            
                        frame_count += 1

                        # Mirror frame for intuitive interaction
                        frame = cv2.flip(frame, 1)
                        h, w = frame.shape[:2]

                        # Calculate running FPS
                        now = time.monotonic()
                        fps = 0.9 * fps + 0.1 / max(now - prev_time, 1e-4)
                        prev_time = now

                        # MediaPipe processing
                        rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
                        results = detector.process(rgb)

                        accuracy = 0.0
                        stability = 0.0
                        pose_name = "Auto-Detecting"
                        category_name = "Auto-Detecting"
                        correction_text = "Aligning posture details..."
                        entry_guidance = "Move fully into camera frame"
                        candidate_scores = {}

                        if results.pose_landmarks:
                            lm_list = results.pose_landmarks[0]
                            
                            # Draw skeleton
                            detector.draw_landmarks(frame, lm_list)

                            # Performance Analysis
                            analysis = analyzer.analyze(detector, lm_list, selected_pose)
                            
                            category_name = analysis["category"]
                            pose_key_active = analysis["detected_pose"]
                            accuracy = analysis["accuracy"]
                            stability = analysis["stability"]
                            entry_guidance = analysis["entry_guidance"]
                            candidate_scores = analysis["candidate_scores"]
                            
                            if pose_key_active != "unknown":
                                pose_name = POSE_DATABASE[pose_key_active]["display_name"]
                                logger.record_accuracy(accuracy)
                                
                                # ---------------------------------------------------------
                                # Pose Hold Timer Logic
                                # ---------------------------------------------------------
                                if accuracy >= 70.0:
                                    if st.session_state.pose_hold_start is None:
                                        st.session_state.pose_hold_start = time.monotonic()
                                    st.session_state.pose_hold_time = time.monotonic() - st.session_state.pose_hold_start
                                    
                                    # Voice cues at milestones (e.g. 5s, 10s, 20s, 30s)
                                    held_sec = int(st.session_state.pose_hold_time)
                                    milestones = [5, 10, 20, 30, 45, 60]
                                    for ms in milestones:
                                        if held_sec >= ms and st.session_state.last_milestone_voiced < ms:
                                            voice_coach.alert("milestone", f"Outstanding alignment, held for {ms} seconds!", cooldown=2.0)
                                            st.session_state.last_milestone_voiced = ms
                                            break
                                else:
                                    st.session_state.pose_hold_start = None
                                    st.session_state.pose_hold_time = 0.0
                                    st.session_state.last_milestone_voiced = 0
                            else:
                                pose_name = "Auto Detecting..."
                                st.session_state.pose_hold_start = None
                                st.session_state.pose_hold_time = 0.0
                                st.session_state.last_milestone_voiced = 0

                            # Handle prioritized voice alerts & coaching feedback
                            if analysis["corrections"]:
                                active_correction = analysis["corrections"][0]
                                correction_text = active_correction["message"]
                                
                                # Voice Coaching Trigger with cooldown logic
                                key = active_correction["key"]
                                fired = voice_coach.alert(key, correction_text, cooldown=voice_cooldown)
                                if fired:
                                    if "perfect" not in key and key != "no_pose":
                                        logger.record_correction(key)
                            else:
                                correction_text = "Good alignment! Maintain posture."
                        else:
                            # Voice alert for no pose visible
                            voice_coach.alert("no_pose", "Step fully into the camera view.", cooldown=12.0)
                            correction_text = "No pose detected - step in front of the camera"
                            st.session_state.pose_hold_start = None
                            st.session_state.pose_hold_time = 0.0
                            st.session_state.last_milestone_voiced = 0

                        # Dynamic stream layout (optimized: redraw every 3 frames to reduce lag)
                        if frame_count % 3 == 0:
                            indicators_html = f"""
                            <div class="glass-card" style="margin-top: 1rem; border-color: rgba(139, 92, 246, 0.4);">
                                <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 0.75rem;">
                                    <span style="font-size: 1.1rem; font-weight: 600; color: #c084fc;">Active Pose: {pose_name}</span>
                                    <span style="background: rgba(255, 255, 255, 0.08); padding: 0.2rem 0.6rem; border-radius: 6px; font-size: 0.8rem; color: #9ca3af; font-family: monospace;">FPS: {fps:.0f}</span>
                                </div>
                                <div style="display: grid; grid-template-columns: repeat(4, 1fr); gap: 0.75rem; text-align: center; margin-bottom: 0.75rem;">
                                    <div style="background: rgba(17, 24, 39, 0.4); padding: 0.5rem; border-radius: 8px;">
                                        <div style="font-size: 1.3rem; font-weight: 800; color: #c084fc; white-space:nowrap; overflow:hidden;">{category_name}</div>
                                        <div style="font-size: 0.65rem; color: #9ca3af; text-transform: uppercase;">Category</div>
                                    </div>
                                    <div style="background: rgba(17, 24, 39, 0.4); padding: 0.5rem; border-radius: 8px;">
                                        <div style="font-size: 1.4rem; font-weight: 800; color: #f472b6;">{accuracy:.0f}%</div>
                                        <div style="font-size: 0.65rem; color: #9ca3af; text-transform: uppercase;">Confidence</div>
                                    </div>
                                    <div style="background: rgba(17, 24, 39, 0.4); padding: 0.5rem; border-radius: 8px;">
                                        <div style="font-size: 1.4rem; font-weight: 800; color: #818cf8;">{stability:.0f}%</div>
                                        <div style="font-size: 0.65rem; color: #9ca3af; text-transform: uppercase;">Stability</div>
                                    </div>
                                    <div style="background: rgba(17, 24, 39, 0.4); padding: 0.5rem; border-radius: 8px;">
                                        <div style="font-size: 1.4rem; font-weight: 800; color: #10b981;">{st.session_state.pose_hold_time:.0f}s</div>
                                        <div style="font-size: 0.65rem; color: #9ca3af; text-transform: uppercase;">Hold Time</div>
                                    </div>
                                </div>
                                <div style="border-top: 1px solid rgba(255, 255, 255, 0.05); padding-top: 0.5rem; margin-bottom: 0.5rem;">
                                    <span style="font-size: 0.7rem; color: #9ca3af; text-transform: uppercase; display: block;">Guidance Instructions:</span>
                                    <div style="color: #9ca3af; font-size: 0.9rem;">🧭 {entry_guidance}</div>
                                </div>
                                <div style="border-top: 1px solid rgba(255, 255, 255, 0.05); padding-top: 0.5rem;">
                                    <span style="font-size: 0.7rem; color: #9ca3af; text-transform: uppercase; display: block;">Coaching Feedback:</span>
                                    <div style="color: #f3f4f6; font-size: 1.05rem; font-weight: 600;">🧘 {correction_text}</div>
                                </div>
                            </div>
                            """
                            indicators_placeholder.markdown(indicators_html, unsafe_allow_html=True)

                        # Render processed webcam frame to Streamlit empty spot
                        frame_rgb_to_st = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
                        frame_placeholder.image(frame_rgb_to_st, channels="RGB", use_container_width=True)

                        # Render dynamic Leaderboard and Debug angles if toggled
                        if show_debug and (frame_count % 3 == 0):
                            debug_html = f"""
                            <div class="glass-card" style="margin-top: 1rem; border-color: rgba(244, 114, 182, 0.25);">
                                <h4 style="margin-top: 0; color: #f472b6; margin-bottom:0.75rem;">AI Diagnostics / Joint Angles Overlay</h4>
                                <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 0.75rem; font-size: 0.85rem; color: #e5e7eb;">
                            """
                            if results.pose_landmarks and "angles" in analysis:
                                for angle_label, val in analysis["angles"].items():
                                    debug_html += f"<div><b>{angle_label}:</b> {val}°</div>"
                            else:
                                debug_html += "<div style='grid-column: 1 / span 2; color:#9ca3af;'>Waiting for active joint estimations...</div>"
                            
                            debug_html += "</div></div>"
                            
                            # Render Candidate Scores Distribution
                            if candidate_scores:
                                debug_html += f"""
                                <div class="glass-card" style="margin-top: 1rem; border-color: rgba(129, 140, 248, 0.25);">
                                    <h4 style="margin-top: 0; color: #818cf8; margin-bottom: 0.5rem;">Candidate Pose Scores ({category_name} Category)</h4>
                                    <div style="font-size: 0.85rem; color: #e5e7eb;">
                                """
                                for c_name, score in candidate_scores.items():
                                    debug_html += f"""
                                    <div style="margin-bottom: 0.4rem;">
                                        <div style="display: flex; justify-content: space-between; margin-bottom: 0.15rem;">
                                            <span>{c_name}</span>
                                            <b>{score:.0f}%</b>
                                        </div>
                                        <div style="background: rgba(255,255,255,0.05); height: 6px; border-radius: 3px;">
                                            <div style="background: linear-gradient(90deg, #6366f1, #c084fc); width: {score}%; height: 6px; border-radius: 3px;"></div>
                                        </div>
                                    </div>
                                    """
                                debug_html += "</div></div>"

                            chart_placeholder.markdown(debug_html, unsafe_allow_html=True)
                        else:
                            chart_placeholder.empty()

                        time.sleep(0.01)  # tiny sleep to yield processor thread

                finally:
                    cap.release()
                    frame_placeholder.empty()
                    indicators_placeholder.empty()
                    chart_placeholder.empty()
        else:
            # Standby screen when webcam inactive
            st.info("AI Coaching is currently offline. Press 'Start AI Coaching' above to open your camera.")

# =========================================================================
# PAGE: UPLOAD IMAGE MODE
# =========================================================================
elif page == "Upload Image Mode":
    render_title_section("IMAGE ANALYZER", "Enhanced AI Diagnostics for Static Posture Analysis")
    
    st.markdown(
        """
        <div class="glass-card" style="margin-bottom: 2.0rem;">
            <h4 style="margin-top: 0; color: #818cf8; margin-bottom: 0.5rem;">Upload Guidelines</h4>
            <ul style="color: #9ca3af; margin-bottom: 0; padding-left: 1.2rem; line-height: 1.5;">
                <li>Supported formats: JPG, JPEG, PNG</li>
                <li>Ensure the full body is visible in the frame</li>
                <li>Good lighting helps with pose detection accuracy</li>
                <li>The system uses multi-stage preprocessing to enhance low-quality images</li>
            </ul>
        </div>
        """,
        unsafe_allow_html=True
    )
    
    uploaded_file = st.file_uploader("Choose an image...", type=["jpg", "jpeg", "png"])

    if uploaded_file:
        try:
            # Process uploaded image
            img_cv = ImagePreprocessor.process_to_cv2(uploaded_file)
            if img_cv is not None:
                col1, col2 = st.columns([1, 1])
                with col1:
                    st.markdown("### Source Image & Detection")
                    
                    # Use enhanced preprocessing pipeline for uploaded images
                    try:
                        # Run enhanced preprocessing pipeline directly from memory
                        success, processed_img, stage_name, results, original_resized = ImagePreprocessor.run_detection_pipeline(img_cv, upload_detector)
                        
                        if success and results and results.pose_landmarks:
                            annotated = processed_img.copy()
                            upload_detector.draw_landmarks(annotated, results.pose_landmarks[0])
                            st.image(cv2.cvtColor(annotated, cv2.COLOR_BGR2RGB), use_container_width=True)
                            st.caption(f"✓ Pose detected on {stage_name}")
                        else:
                            # Show original image if detection failed
                            st.image(cv2.cvtColor(img_cv, cv2.COLOR_BGR2RGB), use_container_width=True)
                            st.warning("⚠ No pose skeleton detected in any preprocessing stage.")
                    except Exception as e:
                        st.error(f"Preprocessing error: {str(e)}")
                        st.image(cv2.cvtColor(img_cv, cv2.COLOR_BGR2RGB), use_container_width=True)
                
                with col2:
                    st.markdown("### Diagnostic Metrics")
                    
                    # Use robust results if successful, else fallback to basic
                    target_results = results if (success and results and hasattr(results, 'pose_landmarks') and results.pose_landmarks) else None
                    if not target_results:
                        target_results = upload_detector.process(cv2.cvtColor(img_cv, cv2.COLOR_BGR2RGB))
                    
                    if target_results and target_results.pose_landmarks:
                        try:
                            analysis = analyzer.analyze(upload_detector, target_results.pose_landmarks[0], None, is_static=True)
                            
                            # Display metrics
                            col_m1, col_m2 = st.columns(2)
                            with col_m1:
                                st.metric("Confidence", f"{analysis['confidence']:.1f}%")
                            with col_m2:
                                st.metric("Stability", f"{analysis['stability']:.1f}%")
                            
                            if analysis.get("is_low_confidence", False):
                                st.warning("⚠ Pose Uncertain — confidence below threshold")
                            
                            detected = analysis['detected_pose']
                            if detected != 'unknown':
                                display = POSE_DATABASE.get(detected, {}).get('display_name', detected)
                                st.success(f"**Detected Pose:** {display}")
                            else:
                                st.info("**Detected Pose:** Pose Uncertain")
                            
                            st.write(f"**Category:** {analysis['category']}")
                            if analysis.get('category_reason'):
                                st.caption(f"Reason: {analysis['category_reason']}")
                            
                            # Debug Panel: Top Candidate Poses
                            candidate_scores = analysis.get("candidate_scores", {})
                            if candidate_scores:
                                st.markdown("**✅ Accepted Candidate Poses:**")
                                sorted_candidates = sorted(candidate_scores.items(), key=lambda x: x[1], reverse=True)
                                for pose_name, score in sorted_candidates[:5]:
                                    st.write(f"- {pose_name} → {score:.1f}%")
                            
                            # Debug Panel: Rejected Poses
                            rejected = analysis.get("rejected_poses", {})
                            if rejected:
                                with st.expander("🚫 Rejected Poses (Hard Filter)"):
                                    for pose_name, reasons in rejected.items():
                                        st.write(f"**{pose_name}:**")
                                        for r in reasons:
                                            st.write(f"  • {r}")
                            
                            # Body Orientation Metrics
                            orientation = analysis.get("orientation", {})
                            if orientation:
                                with st.expander("📐 Body Orientation Metrics"):
                                    st.json(orientation)
                            
                            if analysis.get("angles"):
                                with st.expander("🦴 Joint Angles"):
                                    st.json(analysis["angles"])
                            
                            if analysis.get("corrections"):
                                st.write("**Corrections:**")
                                for correction in analysis["corrections"][:3]:
                                    st.write(f"• {correction['message']}")
                        except Exception as e:
                            st.warning(f"Analysis error: {str(e)}")
                    else:
                        st.info("No pose skeleton detected. Try:\n- Better lighting\n- Full body in frame\n- Higher quality image")
            else:
                st.error("Failed to decode image. Try:\n- Different format (JPG/PNG)\n- Smaller file size\n- Standard resolution")
        except Exception as e:
            st.error(f"Error processing upload: {str(e)}")
            st.info("Please try uploading a different image or check the file format.")
    else:
        st.info("Upload a clear image to begin hierarchical posture classification.")

# =========================================================================
# PAGE: YOGA RECOMMENDATION MODE
# =========================================================================
elif page == "Yoga Recommendation Mode":
    # Netflix-style card CSS for recommendation page
    st.markdown(
        """
        <style>
        .rec-title {
            font-size: 2.8rem;
            font-weight: 800;
            background: linear-gradient(90deg, #38bdf8 0%, #a78bfa 50%, #f472b6 100%);
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
            text-align: center;
            margin-bottom: 0.15rem;
        }
        .rec-subtitle {
            text-align: center;
            color: #9ca3af;
            font-size: 1.1rem;
            margin-bottom: 1.5rem;
        }
        .video-card {
            background: rgba(15, 23, 42, 0.75);
            border: 1px solid rgba(56, 189, 248, 0.18);
            border-radius: 16px;
            overflow: hidden;
            margin-bottom: 1.5rem;
            transition: border-color 0.3s ease, box-shadow 0.3s ease;
        }
        .video-card:hover {
            border-color: rgba(56, 189, 248, 0.45);
            box-shadow: 0 0 24px rgba(56, 189, 248, 0.12);
        }
        .video-card-body {
            padding: 1rem 1.1rem 1.1rem 1.1rem;
        }
        .video-card-title-row {
            display: flex;
            justify-content: space-between;
            align-items: flex-start;
            margin-bottom: 0.45rem;
            gap: 0.5rem;
        }
        .video-card-title {
            font-size: 1rem;
            font-weight: 700;
            color: #e2e8f0;
            line-height: 1.35;
        }
        .badge {
            display: inline-block;
            padding: 0.15rem 0.55rem;
            border-radius: 6px;
            font-size: 0.7rem;
            font-weight: 700;
            white-space: nowrap;
            flex-shrink: 0;
        }
        .badge-beginner { background: rgba(16, 185, 129, 0.18); color: #34d399; border: 1px solid rgba(16, 185, 129, 0.35); }
        .badge-intermediate { background: rgba(245, 158, 11, 0.18); color: #fbbf24; border: 1px solid rgba(245, 158, 11, 0.35); }
        .badge-advanced { background: rgba(239, 68, 68, 0.18); color: #f87171; border: 1px solid rgba(239, 68, 68, 0.35); }
        .video-card-desc {
            font-size: 0.85rem;
            color: #94a3b8;
            line-height: 1.45;
            margin-bottom: 0.6rem;
        }
        .video-card-benefits {
            font-size: 0.78rem;
            color: #38bdf8;
            font-weight: 600;
            margin-bottom: 0.75rem;
        }
        .video-card-tags {
            display: flex;
            flex-wrap: wrap;
            gap: 0.4rem;
            align-items: center;
        }
        .tag-pill {
            display: inline-block;
            padding: 0.18rem 0.55rem;
            border-radius: 999px;
            font-size: 0.68rem;
            font-weight: 600;
            background: rgba(255, 255, 255, 0.06);
            color: #9ca3af;
            border: 1px solid rgba(255, 255, 255, 0.08);
        }
        .watch-btn {
            display: inline-flex;
            align-items: center;
            gap: 0.3rem;
            padding: 0.2rem 0.6rem;
            border-radius: 999px;
            font-size: 0.7rem;
            font-weight: 700;
            background: rgba(56, 189, 248, 0.15);
            color: #38bdf8;
            border: 1px solid rgba(56, 189, 248, 0.3);
            text-decoration: none;
            cursor: pointer;
        }
        </style>
        """,
        unsafe_allow_html=True
    )

    # --- Page Header ---
    st.markdown('<div class="rec-title">Yoga Search & Discovery</div>', unsafe_allow_html=True)
    st.markdown('<div class="rec-subtitle">Find yoga tutorials for wellness and fitness goals</div>', unsafe_allow_html=True)

    # --- Search Bar ---
    if "rec_search_query" not in st.session_state:
        st.session_state.rec_search_query = ""

    col_input, col_btn = st.columns([4, 1])
    with col_input:
        search_query = st.text_input(
            "Search your wellness goal",
            value=st.session_state.rec_search_query,
            placeholder="e.g. stress relief, back pain, weight loss, flexibility...",
            label_visibility="collapsed",
            key="rec_search_input"
        )
    with col_btn:
        st.button("🔍 Search", use_container_width=True)

    st.session_state.rec_search_query = search_query

    # --- Quick Suggestion Chips ---
    st.markdown("**💡 Quick Suggestions:**")
    suggestions = [
        ("Back Pain", "back pain"),
        ("Stress Relief", "stress relief"),
        ("Flexibility", "flexibility"),
        ("Weight Loss", "weight loss"),
        ("Neck Pain", "neck pain"),
        ("Beginner", "beginner yoga"),
    ]
    chip_cols = st.columns(len(suggestions))
    for idx, (label, search_val) in enumerate(suggestions):
        with chip_cols[idx]:
            if st.button(label, key=f"suggest_{idx}", use_container_width=True):
                st.session_state.rec_search_query = search_val
                st.rerun()

    st.divider()

    # --- Results Section ---
    query_text = st.session_state.rec_search_query.strip()

    if query_text:
        st.markdown(f"Results for '*{query_text}*'  &nbsp; **+ AI**", unsafe_allow_html=True)
        st.markdown("")

        videos = YogaRecommendationEngine.get_videos_for_query(query_text)

        if videos:
            # Render in rows of 3 — Netflix-style cards with embedded YouTube
            for i in range(0, len(videos), 3):
                cols = st.columns(3, gap="medium")
                for j in range(3):
                    if i + j < len(videos):
                        video = videos[i + j]
                        video_url = video["url"]
                        parsed_id = YogaRecommendationEngine.extract_youtube_id(video_url)

                        # Difficulty badge class
                        diff = video.get("difficulty", "Beginner")
                        if diff == "Beginner":
                            badge_class = "badge-beginner"
                        elif diff == "Intermediate":
                            badge_class = "badge-intermediate"
                        else:
                            badge_class = "badge-advanced"

                        # Build tag pills HTML
                        tags = video.get("tags", [])
                        duration = video.get("duration", "")
                        tag_pills = ""
                        if tags:
                            for t in tags:
                                tag_pills += f'<span class="tag-pill">{t}</span>'
                        if duration:
                            tag_pills += f'<span class="tag-pill">{duration}</span>'

                        # Benefits text
                        benefits = video.get("benefits", [])
                        benefits_text = " · ".join(benefits) if benefits else ""

                        with cols[j]:
                            # Embedded YouTube player via st.video
                            st.video(video_url)

                            # Card body with title, badge, description, benefits, tags
                            card_html = f"""
                            <div class="video-card-body">
                                <div class="video-card-title-row">
                                    <span class="video-card-title">{video['title']}</span>
                                    <span class="badge {badge_class}">{diff}</span>
                                </div>
                                <div class="video-card-desc">{video['description']}</div>
                                <div class="video-card-benefits">{benefits_text}</div>
                                <div class="video-card-tags">
                                    {tag_pills}
                                    <a href="{video_url}" target="_blank" class="watch-btn">▶ Watch</a>
                                </div>
                            </div>
                            """
                            st.markdown(card_html, unsafe_allow_html=True)
        else:
            st.warning(f'No tutorials found for "{query_text}". Try one of the quick suggestions above!')
    else:
        # Empty state
        st.markdown("---")
        st.markdown(
            """
            ### 🧘 Discovery Hub Active

            Type any wellness goal in the search bar above to find targeted yoga tutorials.

            **Try searching for:**
            - *"back pain"* — stretches for spinal relief
            - *"stress relief"* — calming breathing flows
            - *"weight loss"* — power vinyasa flows
            - *"flexibility"* — deep hip and hamstring stretches
            - *"beginner yoga"* — gentle starter routines
            """
        )


# =========================================================================
# PAGE: ABOUT PROJECT
# =========================================================================
elif page == "About Project":
    render_title_section("PROJECT METRICS", "Architecture & Technical Specifications")

    col_stack, col_arch = st.columns([1, 1])

    with col_stack:
        st.markdown("### System Architecture")
        
        arch_details = """
        <p style="color:#d1d5db; line-height:1.6; font-size:0.95rem;">
            This system runs entirely locally on Windows to offer real-time computer vision training without sending your camera feed to external cloud servers.
        </p>
        <ul style="color:#9ca3af; font-size:0.95rem; line-height:1.6; padding-left: 1.2rem;">
            <li><b>Hierarchical Category Classifier:</b> Groups body layouts into high-level Categories first before analyzing candidate poses, solving splay conflicts.</li>
            <li><b>Computer Vision Model:</b> MediaPipe Pose Landmarker utilizing full-body landmarks (33 keypoints in 3D).</li>
            <li><b>Biomechanical Features:</b> Angle calculators utilizing vector geometry, slopes, splay lines (NumPy).</li>
            <li><b>Pose locking & Temporal Smoothing:</b> Lock mechanism retaining stable pose classification and majority vote rolling frame buffers preventing pose flickering.</li>
            <li><b>Visibility Warnings:</b> Pauses estimation if crucial joints exit the camera frame boundary.</li>
            <li><b>Vocal Guide:</b> Thread-safe offline pyttsx3, prioritizing single high-priority corrections.</li>
        </ul>
        """
        draw_card("Local Computations", arch_details)

    with col_arch:
        st.markdown("### Tech Stack Used")
        
        stack_html = """
        <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 1rem; font-size: 0.95rem;">
            <div style="background: rgba(255, 255, 255, 0.03); border: 1px solid rgba(255, 255, 255, 0.05); padding: 0.75rem; border-radius: 8px;">
                <b style="color: #c084fc;">Streamlit</b><br>
                <span style="color: #9ca3af;">Frontend Dashboard</span>
            </div>
            <div style="background: rgba(255, 255, 255, 0.03); border: 1px solid rgba(255, 255, 255, 0.05); padding: 0.75rem; border-radius: 8px;">
                <b style="color: #c084fc;">MediaPipe</b><br>
                <span style="color: #9ca3af;">Full Skeleton Extraction</span>
            </div>
            <div style="background: rgba(255, 255, 255, 0.03); border: 1px solid rgba(255, 255, 255, 0.05); padding: 0.75rem; border-radius: 8px;">
                <b style="color: #c084fc;">OpenCV</b><br>
                <span style="color: #9ca3af;">Webcam Capture & Drawing</span>
            </div>
            <div style="background: rgba(255, 255, 255, 0.03); border: 1px solid rgba(255, 255, 255, 0.05); padding: 0.75rem; border-radius: 8px;">
                <b style="color: #c084fc;">pyttsx3</b><br>
                <span style="color: #9ca3af;">Offline Threaded TTS</span>
            </div>
            <div style="background: rgba(255, 255, 255, 0.03); border: 1px solid rgba(255, 255, 255, 0.05); padding: 0.75rem; border-radius: 8px;">
                <b style="color: #c084fc;">NumPy</b><br>
                <span style="color: #9ca3af;">Vector Geometry Calculations</span>
            </div>
            <div style="background: rgba(255, 255, 255, 0.03); border: 1px solid rgba(255, 255, 255, 0.05); padding: 0.75rem; border-radius: 8px;">
                <b style="color: #c084fc;">JSON Logs</b><br>
                <span style="color: #9ca3af;">Session Tracker Data</span>
            </div>
        </div>
        """
        draw_card("Developer Specifications", stack_html)

# Add dynamic project footer
st.sidebar.markdown(
    """
    <div style="position: fixed; bottom: 1rem; width: 14%; text-align: center; border-top: 1px solid rgba(255,255,255,0.05); padding-top:0.5rem;">
        <span style="color:#4b5563; font-size:0.75rem;">AI Yoga Coach v2.0.0</span>
    </div>
    """,
    unsafe_allow_html=True
)
